oncokb/oncokb-public

app/scripts/controllers/genes.js
Due to API structure change, it returns highestSensitveLevel and highestResistencLevel instead of highestLevel
=> Fix level issue in genes page

k8s/oncokb-public-local.yml, pom.xml, src/main/docker/app.yml
Liquibase sometimes lock the database when there is an issue restarting the pod. This should be disabled cause you are not expecting to modify the DB schema in production
=> Do not use liquibase in production

src/main/java/org/mskcc/cbio/oncokb/web/rest/SitemapResource.java
The certificate is attached on the ingress level and not propagate to pods
Within the cluster, all connections are to http which will cause issue in the sitemap generation.
We only want to show the result in google with https anyway, so hard code to https for now
This solves https://github.com/oncokb/oncokb/issues/1832
=> Hard code the protocol to https

k8s/oncokb-public-local.yml, pom.xml, src/main/docker/app.yml
This solution is coming from https://stackoverflow.com/questions/30792268/loggerfactory-is-not-a-logback-loggercontext-but-logback-is-on-the-classpath
This fixes https://github.com/oncokb/oncokb/issues/1962
=> Remove logback-classic from thymeleaf

.github/release-drafter.yml, k8s/oncokb-public-local.yml, pom.xml, src/main/docker/app.yml
Another attempt to address https://github.com/oncokb/oncokb/issues/1962
=> Exclude slf4j from jslack to avoid duplicate slf4j dependencies

.github/workflows/sentry-release.yml
This is related to https://github.com/oncokb/oncokb/issues/2035
=> Publish sentry release after make a GitHub release

.jhipster/TokenStats.json, .yo-rc.json, src/main/java/org/mskcc/cbio/oncokb/domain/TokenStats.java, src/main/java/org/mskcc/cbio/oncokb/querydomain/UserTokenUsage.java, src/main/java/org/mskcc/cbio/oncokb/repository/TokenStatsRepository.java, src/main/java/org/mskcc/cbio/oncokb/service/TokenStatsService.java, src/main/java/org/mskcc/cbio/oncokb/service/impl/TokenServiceImpl.java, src/main/java/org/mskcc/cbio/oncokb/service/impl/TokenStatsServiceImpl.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/ApiProxy.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java, src/main/resources/config/liquibase/changelog/20190826144658_added_entity_TokenStats.xml, src/main/resources/config/liquibase/fake-data/token_stats.csv, src/test/java/org/mskcc/cbio/oncokb/web/rest/TokenStatsResourceIT.java
We should not update the token based on the api call, that will mess up with the cache.
This fixes https://github.com/oncokb/oncokb/issues/2095
This is related to https://github.com/oncokb/oncokb/issues/2110
=> Update token usage by cronjob instead of basing on actually API calls

.github/workflows/docker-release.yml, .github/workflows/sentry-release.yml
This fixes https://github.com/oncokb/oncokb/issues/2257
This is related to https://github.com/oncokb/oncokb/issues/1990
=> Automatically publish docker image when a release is published

src/main/resources/config/application-dev.yml, src/main/webapp/app/App.tsx, src/main/webapp/app/index.tsx, src/main/webapp/app/indexUtils.tsx, src/main/webapp/app/store/WindowStore.ts, src/main/webapp/index.html
- Apis would be called before Recaptcha component was rendered during website first rendering. Maybe find a way to make apis be called after component rendered, or apis cannot get latest recaptcha tokens.
- Maybe need to find a way to block each api call until recaptcha get a new token for it.
- Cannot set recaptcha token in localStorage since recaptcha needs time to get new token, localstorage will not update new token in time while apis be called almost in the same time.
- Maybe also need to find a way to judge if recaptcha token is used by other APIs.
=> Problems need to be solved

src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx, src/main/webapp/app/pages/genePage/GenePage.tsx
This implemented 
- https://github.com/oncokb/oncokb/issues/2223 item 1
Gene Page:
Variant Page:
=> Show level column first in the gene/variant page tables

src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/HomePage.tsx, src/main/webapp/app/pages/actionableGenesPage/ActionableGenesPage.tsx, src/main/webapp/app/pages/actionableGenesPage/LevelSelectionRow.tsx, src/main/webapp/app/routes/routes.tsx, src/main/webapp/app/shared/utils/Utils.tsx
This implements 
- https://github.com/oncokb/oncokb/issues/2081
- https://github.com/oncokb/oncokb/issues/2082
But the OncoKB-style-0.2.0-alpha.5 looks like still doesn't have icons for Dx/Px. It only has level colors for Dx/Px.
Below is the demo:
=> Show Tx/Dx/Px seperately on Home Page and Actionable Genes Page

src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/HomePage.tsx, src/main/webapp/app/pages/actionableGenesPage/ActionableGenesPage.tsx, src/main/webapp/app/pages/actionableGenesPage/LevelSelectionRow.tsx, src/main/webapp/app/shared/utils/Utils.tsx
This implemented https://github.com/oncokb/oncokb/issues/2081
Need to be solved: 
Mockup:
- Home Page
- Actionable Gene Page
=> Show Tx/Dx/Px seperately on Home Page and Actionable Genes Page - Stage 2

src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx
This fixes https://github.com/oncokb/oncokb/issues/2366
=> Do not show gene name when alteration includes the gene name in the alteration page

src/main/webapp/app/App.tsx, src/main/webapp/app/store/WindowStore.ts
This fixes https://github.com/oncokb/oncokb/issues/2389
I can reproduce the issue when I block the recaptcha.net
It could just be the recaptcha rendering is slow. In either situation, we should only validate recaptcha when it's rendered.
=> Only execute recaptcha when it's rendered

src/main/webapp/app/components/newAccountForm/NewAccountForm.tsx
This fixes https://github.com/oncokb/oncokb/issues/2575
=> Do not show company info in the license explanation if the section is hidden through url

src/main/java/org/mskcc/cbio/oncokb/config/application/SlackProperties.java, src/main/java/org/mskcc/cbio/oncokb/service/MailService.java, src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java
When map yaml to java variable, we use . before each upper case characters which results to  application.slack.base.u.r.l. This is not what we are expecting in the settings
Signed-off-by: Hongxin <5400599+zhx828@users.noreply.github.com>
=> Fix the slack properties naming issue

src/main/java/org/mskcc/cbio/oncokb/config/application/ApplicationProperties.java, src/main/java/org/mskcc/cbio/oncokb/domain/UserStatusChecks.java, src/main/java/org/mskcc/cbio/oncokb/domain/enumeration/LicenseType.java, src/main/java/org/mskcc/cbio/oncokb/repository/UserMailsRepository.java, src/main/java/org/mskcc/cbio/oncokb/service/MailService.java, src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java, src/main/java/org/mskcc/cbio/oncokb/service/UserMailsService.java, src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/SlackController.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/slack/ActionId.java, src/main/resources/templates/mail/activateFreeTrial.html, src/main/resources/templates/mail/approvalMSKInCommercial.html, src/main/resources/templates/mail/clarifyAcademicUseWithoutInstituteEmail.html, src/main/resources/templates/mail/clarifyLicenseInForProfileCompany.html, src/main/resources/templates/mail/licenseReview.html, src/main/resources/templates/mail/tokenHasBeenExposedToUser.html
- Non-approve buttons have been moved to a dropdown menu for organization
- Clarification and Denial emails can be sent in this menu (ignore embargo for now)
this fixes https://github.com/oncokb/oncokb/issues/2655
=> Add Dropdown Menu to Slack Integration

src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java
Slack blocks were not collapsing automatically when the academic clarification email was sent. Now they automatically collapse to the following block:
=> Fixed clarification email bug

src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java
The `ActionId` of the `BlockActionPayload` corresponding to the `Collapse` option in the dropdown menu is not correctly obtained.
=> fix dropdown bug

src/main/java/org/mskcc/cbio/oncokb/web/rest/ApiProxy.java, src/main/webapp/app/shared/api/generated/API-docs.json, src/main/webapp/app/shared/api/generated/API.ts
We previous only return the api proxy body content, but when it throws error, the response status code from public does not reflect the accurate status from api proxy
This fixes https://github.com/oncokb/oncokb/issues/2678
=> Reflect API proxy response status

src/main/java/org/mskcc/cbio/oncokb/OncokbPublicApp.java, src/main/webapp/app/index.tsx
- This fixes https://github.com/oncokb/oncokb/issues/2691
- The frontend sentry has been disabled already when in localhost.
- We use data-filters in the sentry settings for frontend project
=> Only include sentry when the instance has prod profile

src/main/java/org/mskcc/cbio/oncokb/repository/CompanyRepository.java, src/main/java/org/mskcc/cbio/oncokb/service/CompanyService.java, src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/service/dto/UserDTO.java, src/main/java/org/mskcc/cbio/oncokb/service/impl/CompanyServiceImpl.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/CompanyResource.java, src/main/resources/templates/mail/activateFreeTrial.html, src/main/resources/templates/mail/approvalEmail.html, src/main/webapp/app/components/account/ActivateTrialFinish.tsx, src/main/webapp/app/components/newAccountForm/NewAccountForm.tsx, src/main/webapp/app/components/newCompanyForm/NewCompanyForm.tsx, src/main/webapp/app/shared/api/generated/API-docs.json, src/main/webapp/app/shared/api/generated/API.ts, src/main/webapp/app/shared/select/FormSelectWithLabelField.tsx
This fixes [issue #2770](https://github.com/oncokb/oncokb/issues/2770)
- Only admins will get a company dropdown. 
- When a user is created with a company selected, the user will automatically be linked to the company. 
- Company name and description will be automatically filled.
- Companies cannot have the same name. 
- Add error message when user inputs a name that is already in use.
=> Allow admin to register user using an existing company's info.

src/main/java/org/mskcc/cbio/oncokb/aop/api/APIConditionallyEnabledAspect.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java
Fix error from `disable-registration`
- When db-read-only is false, the method annotated with `APIConditionallyEnabled` was not executed
- Use the joinpoint.proceed() method to execute method when api endpoint is enabled.
Also fixes [issue #2849](https://github.com/oncokb/oncokb/issues/2849)
- Use updated user (one with the newly generated reset key) when sending email
=> Fix disabled endpoint

src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java
This fixes issue: Users that were part of a regular, full licensed company were getting automatically approved and added to company, but did not receive an approval email.
=> Send approval email when regular user is automatically approved

src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/UserUUIDController.java, src/main/webapp/app/pages/CreateCompanyUsersPage.tsx, src/main/webapp/app/pages/userPage/UserPage.tsx, src/main/webapp/app/shared/table/UserTable.tsx, src/main/webapp/app/store/AuthenticationStore.ts
This fixes [issue #2858](https://github.com/oncokb/oncokb/issues/2858)
- Users with at least one renewable token are considered regular, not trial.
- Set `notifyUserOnTrialCreation` to true when creating users in the CreateCompanyUsersPage. Currently, it's only sending the account is created email.
=> Change logic for determining if user is on trial

src/main/java/org/mskcc/cbio/oncokb/OncokbPublicApp.java
We should use the environment variables overwrite the configs instead
=> Do not set the debug/tracesSasmpleRate configs of sentry in the code

src/main/java/org/mskcc/cbio/oncokb/web/rest/CompanyDomainResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/CompanyResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/UserDetailsResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/UserMailsResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/errors/ExceptionTranslator.java
This addresses [issue 2904](https://github.com/oncokb/oncokb/issues/2904) and [issue 2880](https://github.com/oncokb/oncokb/issues/2880)
Both issues were related to the error message shown when a user was already registered.
- Used the solution from [pr](https://github.com/oncokb/oncokb-public/pull/754)
- When the `LoginAlreadyUsedException` or `EmailAlreadyUsedException` are caught in ExceptionTranslator.java, we used HeaderUtil from jhipster to create a header, which adds headers starting with 'X-'
=> Remove headers created with HeaderUtil

src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java
This is related to https://github.com/oncokb/oncokb/issues/2871
- Revert the change made in https://github.com/oncokb/oncokb-public/pull/789
- Auto-approved users will get an approval message on the website after they activate their account, so no need to send an email.
=> Remove approval email for auto approved user

src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java
I noticed a bug on one of the slack webhooks. (https://oncokb.slack.com/archives/GQF05K5TK/p1639686342012700)
This change should fix it.
=> Fix trial account slack visual bug

src/main/java/org/mskcc/cbio/oncokb/service/UserService.java
This fixes https://github.com/oncokb/oncokb/issues/2902
When trial users are added to a trial company, then their tokens expiration date will be the longest of the default trial period (90 days) or their current token's expiration date.
=> Update company trial user's expiration date

src/main/webapp/app/pages/apiAccessGroup/ApiAccessPageNavTab.tsx
This fixes https://github.com/oncokb/oncokb/issues/2906
When redirecting to `/account/register`, the hash parameters were not passed along. 
Adding the `hash` field in the location object fixes this issue.
=> Pass hash parameters from ApiAccessPageNavTab to pages

src/main/java/org/mskcc/cbio/oncokb/config/Constants.java, src/main/java/org/mskcc/cbio/oncokb/domain/TokenStats.java, src/main/java/org/mskcc/cbio/oncokb/repository/TokenStatsRepository.java, src/main/java/org/mskcc/cbio/oncokb/service/TokenStatsService.java, src/main/java/org/mskcc/cbio/oncokb/service/impl/TokenStatsServiceImpl.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/TokenStatsResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/UsageAnalysisController.java, src/main/webapp/app/shared/api/generated/API-docs.json
Added cronjob to 
- retrieve token_stats SQL data
- parse data to txt file
- send file to `oncokb/token-usage/`
- clear token_stats table in the database
This is related to https://github.com/oncokb/oncokb/issues/2635
=> Wrap token_stats to s3

src/main/webapp/app/components/oncokbSearch/OncoKBSearch.tsx, src/main/webapp/app/components/searchOption/SearchOption.tsx
This fixes https://github.com/oncokb/oncokb/issues/2923
- The `appStore` prop was passed incorrectly to `SearchOption` component, so it was undefined.
- Passed the search string to feedback so it is displayed in the modal title
- Title was: `Annotation suggestion for [missing]`
=> Fix appStore undefined in OncoKBSearch

src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/webapp/app/pages/userPage/UserPage.tsx
This fixes https://github.com/oncokb/oncokb/issues/2960
- Check activation status before updating and also in UserPage default to `Regular` account type if user doesn't have any tokens.
- We need `generateTokenForUserIfNotExists` in updateUser because we can activate user in UserPage and the user table.
- Also, when admin sets an inactivated user to activated in UserPage, the `this.userTokens` is not updated so token does not show up.
=> Don't generate token for inactivated users

src/main/java/org/mskcc/cbio/oncokb/domain/TokenStats.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/ApiProxy.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java
This fixes https://github.com/oncokb/oncokb/issues/2954
=> Allow fetching 1M records in token stats pagination for backing up to s3

src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java, src/main/resources/templates/mail/activationEmail.html, src/main/webapp/app/components/account/ActivateAccount.tsx, src/main/webapp/app/shared/api/generated/API-docs.json, src/main/webapp/app/shared/api/generated/API.ts, src/test/java/org/mskcc/cbio/oncokb/web/rest/AccountResourceIT.java
Related to https://github.com/oncokb/oncokb/issues/2995
- The activation URL should be `/account/verify?key=<key>&login=<login>`
- Users without an `activationKey` will not receive an error, but show the appropriate message based on their account status.
- If the login cannot be found or the activationKey does not match, then we throw the error
=> Include user login in activation email

src/main/webapp/app/routes/routes.tsx, src/main/webapp/app/shared/auth/private-route.tsx, src/main/webapp/app/shared/error/error-boundary-route.tsx
Based on https://v5.reactrouter.com/web/api/Route/component, a new component will be rendered every time a route changes which causes unnecessary mount/unmount.
This fixes https://github.com/oncokb/oncokb/issues/2998
=> Use route render instead of component for inline function

src/main/webapp/app/pages/companyPage/CompanyPage.tsx, src/main/webapp/app/pages/userManagement/UserDetailsPage.tsx, src/main/webapp/app/pages/userPage/UserPage.tsx, src/main/webapp/app/shared/table/UserTable.tsx
This fixes https://github.com/oncokb/oncokb/issues/3033
- Admins can verify user email manually through the user page, user table, and company user table.
- Added a button to table's `Status` column to verify email.
- 
- In the User Page, added radio buttons. Once the email is set to 'Verified', then cannot be set back to unverified.
=> Allow admin to manually verify user email

src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java, src/main/webapp/app/components/accountMessage/AccountMessage.tsx, src/main/webapp/app/components/tokenInputGroups/TokenInputGroups.tsx, src/main/webapp/app/pages/AccountPage.tsx, src/main/webapp/app/pages/userPage/UserPage.tsx, src/main/webapp/app/shared/button/ButtonWithTooltip.tsx, src/main/webapp/app/shared/button/CopyButton.tsx, src/main/webapp/app/store/AuthenticationStore.ts
This fixes https://github.com/oncokb/oncokb/issues/3035
- User tokens are sorted by their lengths, so the last token (longest) cannot be deleted.
- Users can generate new token if they have only 1 token. 
- When user generates a new token, the old token will expire in `min(7 days, current expiration)`.
- User can delete any token now. The token's expiration will be applied to another token.
Other:
- Fixed tooltip not showing on disabled buttons.
- `AccountMessage` shows the trial about to expire banner at top of page even when the user logged out, so that is fixed.
=> Allow users to generate a new token.

src/main/java/org/mskcc/cbio/oncokb/service/dto/UserDTO.java, src/main/webapp/app/shared/utils/FormValidationUtils.tsx
- companyName/city/country are required to have at least two characters
- we cannot force the not empty requirement yet because the company model does not have city/country and creating user through company page does not enforce the info
- first/last name are required to have at least two characters and not empty
This fixes https://github.com/oncokb/oncokb/issues/3112
=> Update user info restriction

src/main/java/org/mskcc/cbio/oncokb/config/Constants.java, src/main/java/org/mskcc/cbio/oncokb/security/jwt/TokenProvider.java, src/main/java/org/mskcc/cbio/oncokb/security/uuid/TokenProvider.java, src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java, src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/service/impl/CompanyServiceImpl.java, src/main/java/org/mskcc/cbio/oncokb/util/ObjectUtil.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/SlackController.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/errors/LicenseAgreementNotAcceptedException.java, src/test/java/org/mskcc/cbio/oncokb/service/CompanyServiceIT.java, src/test/java/org/mskcc/cbio/oncokb/service/UserServiceIT.java, src/test/java/org/mskcc/cbio/oncokb/util/ObjectUtilUnitTest.java
This fixes https://github.com/oncokb/oncokb/issues/3174
Reason: A user has not activated their trial license will still have their trial account activation `key`, so this PR (https://github.com/oncokb/oncokb-public/pull/793) prevents the user from logging in. However, if the user later gets added to a regular company, that information should be cleared or else the user not be able to login.
- Fixed trial account agreement link not showing when user who hasn't agreed to terms tries to login. This was due to the OncoKB text replaced with the trademark version in the frontend, but was not reflected in the backend error constant.
- Remove trial account information when a user's license changes to regular or is expired if the trial was never activated. 
- Added a few extra test cases
=> Remove inactivated trial account's information when user license changes to regular

screenshot-test/App.screenshot.js, src/main/java/org/mskcc/cbio/oncokb/config/CacheConfiguration.java, src/main/java/org/mskcc/cbio/oncokb/config/cache/UserCacheResolver.java, src/main/java/org/mskcc/cbio/oncokb/repository/UserDetailsRepository.java, src/main/java/org/mskcc/cbio/oncokb/repository/UserRepository.java, src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/service/dto/UserDTO.java, src/main/java/org/mskcc/cbio/oncokb/service/dto/useradditionalinfo/Activation.java, src/main/java/org/mskcc/cbio/oncokb/service/dto/useradditionalinfo/AdditionalInfoDTO.java, src/main/java/org/mskcc/cbio/oncokb/service/dto/useradditionalinfo/Contact.java, src/main/java/org/mskcc/cbio/oncokb/service/dto/useradditionalinfo/LicenseAgreement.java, src/main/java/org/mskcc/cbio/oncokb/service/dto/useradditionalinfo/TrialAccount.java, src/main/java/org/mskcc/cbio/oncokb/service/dto/useradditionalinfo/UserCompany.java, src/main/java/org/mskcc/cbio/oncokb/service/mapper/UserMapper.java, src/main/webapp/app/config/constants.tsx
This fixes https://github.com/oncokb/oncokb/issues/2342
- Cache `getAllManagedUsers` method in `UserService.java`
- Update `usersToUserDTOs` method to fetch user + user details in bulk
- Update `getNonCompanyUserEmails` method in `UserService.java` to use custom query
- The original query takes about 7-8 seconds, but the custom query takes ~50ms.
=> Improve User Details Page and Company Page's User Dropdown Performances

pom.xml
This is related to https://github.com/oncokb/oncokb/issues/3271
- Update jib to v3.3.0(checked the history, didn't see breaking changes)
- Update default base image to eclipse-temurin. adoptopenjdk is deprecated(https://hub.docker.com/_/adoptopenjdk) and jib has changed to eclipse-temurin in v3.2.0
- Build both amd64 and arm64 images so we can use arm64 image in AWS Graviton server
=> Build multi-platforms docker image using latest jib

src/main/java/org/mskcc/cbio/oncokb/repository/TokenStatsRepository.java
The default JPA deleteBy will load all entities in memory because it's a transection and potentially it can roll back if anything goes wrong. But token stats table could be very big, we should not load all into memory. Using Query annotation together with Modifying will send a SQL query directly. Reference: https://www.baeldung.com/spring-data-jpa-modifying-annotation
This fixes https://github.com/oncokb/oncokb/issues/3314
=> Use SQL query to delete all token stats

src/main/webapp/app/components/calendarButton/CalendarButton.tsx, src/main/webapp/app/components/dateSelector/DateSelector.tsx, src/main/webapp/app/components/dividerWithInfo/DividerWithInfo.module.scss, src/main/webapp/app/components/dividerWithInfo/DividerWithInfo.tsx, src/main/webapp/app/index.scss, src/main/webapp/app/pages/companyPage/CompanyPage.tsx, src/main/webapp/app/pages/userPage/UserPage.tsx
- Add DividerWithInfo component
- Move date selector as a separate component
- Make DateSelector prop `currentDate` optional. When `currentDate` is undefined, the quick extension is based on today
- Vertical align all components within DateSelector
- this fixes https://github.com/oncokb/oncokb/issues/3308
- all users that have trial initiated will be extended to the date admin selects
- allow admin to change trial expiration date
=> Add quick tool to extend trial access

src/main/webapp/app/oncokb-frontend-commons/src/components/SummaryWithRefs.tsx, src/main/webapp/app/pages/actionableGenesPage/ActionableGenesPage.tsx
The tumor type search key will be the code when subtype is selected, therefore the original string array relevantCancerTypes cannot identify the code.
This fixes https://github.com/oncokb/oncokb/issues/3390
=> Fix the relevant tumor type search keyword issue

src/main/webapp/app/components/feedback/FeedbackIcon.tsx, src/main/webapp/app/pages/annotationPage/AlterationTableTabs.tsx
The dimension of the table will overshadow the description because we shifted the table up 30px.
This fixes https://github.com/oncokb/oncokb/issues/3406
=> Bring the tab description to the front

src/main/resources/templates/sitemap/sitemapGeneral.xml, src/main/resources/templates/txt/robots.txt
Do not block the whole /api URL so the pages can be indexed by search engine.
This fixes https://github.com/oncokb/oncokb/issues/3407
=> Update robots.txt and general sitemap

src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx
So the menu can be shown before the tab descriptions. The description has a custom z-index:1
=> Add zIndex to cancer type select in annotation page

src/main/webapp/app/pages/newsPage/ChangedAnnotatonListItem.tsx, src/main/webapp/app/pages/newsPage/NewsPageContent.tsx, src/main/webapp/app/pages/newsPage/UpdatedTxImplListItem.tsx, src/main/webapp/app/pages/newsPage/Util.tsx
the follow up PR for: https://github.com/oncokb/oncokb/issues/3414
if either entry input with `,|/` in `Gene` or `Mutation` columns, they are ignored.
so there is an alteration ink iff there is one gene and one mutation in its respective columns
=> Add alteration links to news page

Dockerfile
The location of deb.debian has been moved to archive. We need to change the source without modifying the node image
=> Update debian imported stretch suite location

src/main/java/org/mskcc/cbio/oncokb/config/SecurityConfiguration.java
The website is used by google analytics 4.
This is related to https://github.com/oncokb/oncokb/issues/3412
=> Allow loading script from googletagmanager.com

src/main/webapp/app/pages/annotationPage/CancerTypeView.tsx
We have tumor type summary designed for cases without any treatment, example: JAK2/OncogenicMutations/Other Tumor Type. We should show the summary even when tx is not applicable.
=> Always show tx section in annotation page

src/main/webapp/app/pages/actionableGenesPage/ActionableGenesPage.tsx
- Only show treatment with FDA level. If the treatment is Dx/Px, then the fda level is not available
- Add key to actionable genes page. Multiple tables will be rendered if the key is different. This helps to differentiate the paginated vs non-paginated tables. The react-table lib has issue recognizing remove props.
This fixes https://github.com/oncokb/oncokb/issues/3521
=> Updates to actionable genes page

src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx
We will try to keep the logo in the same line by shrinking the text on the left until it reaches minimum 300px.
This fixes https://github.com/oncokb/oncokb/issues/3537
=> Keep annotation source logo on the same line of text

src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx, src/main/webapp/app/pages/annotationPage/MutationEffectDescription.tsx
when the allele is unknown but multiple alternative alleles at the same position have mutation effects
This fixes https://github.com/oncokb/oncokb/issues/3552
=> Add link to alteration page in the mutation effect description

src/main/webapp/app/pages/annotationPage/Utils.ts
The sortedBy always returns the ascending order and LEVEL_PRIORITY store the lower priority first.
This fixes https://github.com/oncokb/oncokb/issues/3583
=> Show the highest FDA level among evidence

.eslintignore, .gitignore, jest.conf.js, package.json, src/main/webapp/app/config/constants/regex.spec.ts, src/main/webapp/app/config/constants/regex.ts, src/main/webapp/app/oncokb-frontend-commons/src/components/SummaryWithRefs.tsx, src/main/webapp/app/pages/genePage/GenePage.tsx, webpack/environment.js
This fixes https://github.com/oncokb/oncokb/issues/3599
=> Update reference capture regex && Add Jest unit test

src/main/webapp/app/components/userMessager/UserMessage.tsx
@calvinlu3 let me know whether the time works for you. Also I don't want to show the banner during the AMP conference. Currently it's set up to be displayed on the 19th 0am(GMT) and ends on 27th 0am (GMT).
=> Add service disruption message

src/main/webapp/app/variables.scss
We originally have Precision Oncology Therapies which has been changed to Oncology Therapies. The new headers will only be converted to two lines at 1413px
=> Change extra large cutoff based on the header items

.github/workflows/docker-sentry-release.yml
This fixes https://github.com/oncokb/oncokb/issues/3723
1. Use official sentry github action
2. Update `releaseNamePrefix` and `tagName` parameters to corresponding names in the official sentry action: `version_prefix` and `version`. Refer to https://github.com/getsentry/action-release?tab=readme-ov-file#parameters
I tested these changes on my fork: https://github.com/calvinlu3/oncokb-public/actions/runs/8637933444/job/23681240882
- The step labeled `Create a Sentry.io release in oncokb-public-test` is now passing
- Verified that the Sentry release is available on Sentry.io
=> Use official sentry github action

src/main/webapp/app/pages/companyPage/CompanyPage.tsx
In https://github.com/oncokb/oncokb-public/pull/1088, we introduced simpleConfirmModalType which indicates whether it's to update or delete company. When changing license type with user associated, we need to specify the simpleConfirmModalType to UPDATE_COMPANY.
This fixes https://github.com/oncokb/oncokb-pipeline/issues/344
=> Update confirm model type when changing license type with user associated

src/main/webapp/app/routes/routes.tsx, src/main/webapp/app/shared/auth/RecaptchaBoundaryRoute.tsx, src/main/webapp/app/shared/auth/private-route.tsx, src/main/webapp/app/shared/error/error-boundary-route.tsx, src/main/webapp/app/shared/route/OncokbRoute.tsx
fixes onockb/oncokb-pipeline#321
=> Added canonical link to html head

src/main/webapp/app/shared/route/OncokbRoute.tsx
The canonical link was broken so I think that's why validation failed. I also checked if we're making these [common mistakes](https://developers.google.com/search/blog/2013/04/5-common-mistakes-with-relcanonical) and I do not think we are.
=> Fixed broken canonical link

src/main/webapp/app/config/constants/regex.spec.ts, src/main/webapp/app/config/constants/regex.ts
This is related to https://github.com/oncokb/oncokb-pipeline/issues/359
=> Update reference regex to support 1 level of nested parenthesis

src/main/webapp/app/components/Header.tsx, src/main/webapp/app/layout.scss, src/main/webapp/app/pages/menus/account.tsx
This fixes https://github.com/oncokb/oncokb/issues/3742
=> Center align navbar text and remove account text for screen less than 1500px

src/main/webapp/app/pages/aboutGroup/FdaRecognitionPage.tsx
This is a linkout URL which needs to include the origin.
This fixes https://github.com/oncokb/oncokb/issues/3765
=> Fix FDA recognition letter linkout

src/main/java/org/mskcc/cbio/oncokb/config/ClockConfig.java, src/main/java/org/mskcc/cbio/oncokb/config/Constants.java, src/main/java/org/mskcc/cbio/oncokb/util/TimeUtil.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/UsageAnalysisController.java, src/test/java/org/mskcc/cbio/oncokb/web/rest/UsageAnalysisControllerIT.java
I created a private `MockS3Data` class with a `files` property which generates and stores the mock JSON S3 files and the expected responses from all the endpoints. I hard coded a seed for the random number generator so that the tests always have the same data passed to them which should make it easier to debug any breaks.
I made the class private since it seemed unnecessary to create file for a class that is only needed once. 
I think I may have caught some bugs with some endpoints, but I opted to maintain the same behavior so the current expected response data may not look quite right. My goal is to make it obvious what the behavior changes are when I make the 3 year timeline change in `UsageAnalysisController`.
=> Added unit test to usage metrics endpoints

src/main/webapp/app/pages/annotationPage/MutationEffectDescription.tsx
Separate leading sentence when mutation effect comes from relevant alteration.
This fixes https://github.com/oncokb/oncokb/issues/3710
=> Separate leading sentence when ME comes from relevant alteration

src/main/webapp/app/config/constants.tsx, src/main/webapp/app/index.tsx
We try to reload the page when we see 401 code so user can use server side returned token. However, in login page, the /api/authentication api will return 401 when a token is expired. Here in this fix, we white list the API from being reloaded.
This fixes https://github.com/oncokb/oncokb/issues/3785
=> Do not reload the page when authentication endpoint failed

src/main/webapp/app/config/constants/regex.spec.ts, src/main/webapp/app/config/constants/regex.ts
This fixes https://github.com/oncokb/oncokb/issues/3790
=> Allow new line in text validation

src/main/docker/smtp-server.yml, src/main/resources/config/application-dev.yml
closes oncokb/oncokb-pipeline#535
This [mock server](https://github.com/gessnerfl/fake-smtp-server) just captures the email requests and gives you a UI to see what was sent.
=> Added mock email server

src/main/java/org/mskcc/cbio/oncokb/config/SecurityConfiguration.java, src/main/webapp/app/pages/apiAccessGroup/APIAccessPage.tsx
resolves https://github.com/oncokb/oncokb-pipeline/issues/665
=> add all annotated variants download button to api access page

src/main/java/org/mskcc/cbio/oncokb/OncokbPublicApp.java
Resolves https://github.com/oncokb/oncokb/issues/3866
No need to catch this exception in Sentry. It is for the user
=> Ignore TokenExpiredException in Sentry

src/main/resources/templates/mail/activationEmail.html, src/main/resources/templates/mail/verifyEmailBeforeAccountExpires.html, src/main/webapp/app/pages/userPage/UserPage.tsx
fixes https://github.com/oncokb/oncokb-pipeline/issues/901
Some users had links with `+` in their email. This was breaking our validation link because this is treated as a space in URL encoding. I updated our email templates so that the email is URL encoded. I noticed a similar issue with a link in our admin pages.
=> Fix Verify Email Link Not Working
