app/scripts/controllers/gene.js
related to https://github.com/oncokb/oncokb/issues/353
=> exclude fusion from the mutation mapper diagram

app/views/main.html
=> Remove subtitle

app/scripts/app.js, app/scripts/controllers/gene.js, app/scripts/controllers/genes.js, app/scripts/controllers/home.js, app/scripts/services/api.js
Should be merged at same with with pull request https://github.com/oncokb/oncokb/pull/472
=> API updates due to new structure of public API

app/views/news.html, app/views/team.html
=> Update News/Team pages

app/scripts/controllers/actionalGenes.js, app/scripts/controllers/gene.js, app/scripts/services/utils.js, app/styles/_actionable.scss, app/styles/_gene.scss, app/styles/_home.scss, app/styles/main.scss, app/views/actionalGenes.html, app/views/gene.html
Use alteration name instead of alteration in actionable genes table
=> Add variant link in actionable genes page; Disable variant link if contain slash

app/styles/_gene.scss
=> Fix mutation mapper button hover over style issue

app/scripts/app.js, app/styles/_gene.scss, app/styles/_mixins.scss, app/styles/_nav.scss
To implement fixed header animation:
=> Make Gene page header fixed : track scroll top

app/views/dataaccess.html
This solves issue https://github.com/oncokb/oncokb/issues/847 and #158
=> Add OncoKB Annotator info in the Data Access page

app/scripts/controllers/cancerGenes.js, app/views/about.html, app/views/cancerGenes.html, app/views/team.html
=> Cancer Genes page update

.editorconfig, app/index.html, app/scripts/app.js, app/scripts/controllers/actionalGenes.js, app/styles/_layout.scss, app/styles/_nav.scss, app/styles/_searchIcon.scss, app/styles/_vars.scss, app/views/actionalGenes.html, app/views/cancerGenes.html, app/views/gene.html, app/views/license.html, app/views/news.html
- Update header with fewer tabs
- Show the first line of the footer in 13inch laptop
- Consolidated all OncoKB email addresses to contact@oncokb.org
=> Interface updates

app/styles/_home.scss, app/styles/_layout.scss
=> Edit styles to make the page showing footer in 13inch laptop

app/views/cancerGenes.html
Signed-off-by: Hongxin Zhang <hongxin@cbio.mskcc.org>
=> Show the latest update in the cancer genes table page

Gruntfile.js
The sorting from the library does not work. Solution based on https://stackoverflow.com/questions/32952514/ng-table-yeoman-sorting-works-fine-in-development-but-breaks-in-production
=> Fix a weired issue with ng-table

app/scripts/app.js, bower.json, package-lock.json
This solves https://github.com/oncokb/oncokb/issues/1583
=> Include R2 descriptions

app/scripts/controllers/news.js
Signed-off-by: Hongxin Zhang <jackson.zhang.828@gmail.com>
=> update special characters

app/scripts/controllers/gene.js, app/styles/_gene.scss, app/views/gene.html
This solves https://github.com/oncokb/oncokb/issues/1626
=> Fix lollipop issue

app/scripts/controllers/actionalGenes.js
This solves https://github.com/oncokb/oncokb-public/issues/283
=> Support 2A, 3A in the actionableGenes URL

app/scripts/controllers/actionalGenes.js, app/scripts/services/api.js, app/styles/_actionable.scss, app/views/actionalGenes.html
Replace tumor type filter dropdown to a typeahead component
When user pastes content, automatically trigger the filtering
=> Support annotate selected tumor type

app/scripts/controllers/actionalGenes.js, app/styles/_layout.scss, app/views/actionalGenes.html
This fixes https://github.com/oncokb/oncokb/issues/1655
=> Actionable genes page update

app/index.html, app/scripts/directives/search-box.js, app/scripts/directives/search-icon.js, app/scripts/directives/suggest-curation.js, app/styles/_searchBox.scss, app/views/cancerGenes.html, app/views/searchBox.html, app/views/suggestCuration.html
This solves https://github.com/oncokb/oncokb/issues/1688
=> Allow user suggests annotation in the search result

.gitignore, k8s/oncokb-public-local.yml, src/main/java/org/mskcc/cbio/oncokb/security/uuid/TokenProvider.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/UserUUIDController.java, src/main/webapp/app/components/SmallPageContainer.tsx, src/main/webapp/app/config/constants.ts, src/main/webapp/app/index.scss, src/main/webapp/app/pages/AccountPage.tsx, src/main/webapp/app/shared/icons/InfoIcon.tsx
- Ignore files from v1
- The token expiration day will be extended after user verifies the account
This solves https://github.com/oncokb/oncokb/issues/1817
=> Fix the time diff issue & always assign same expiration day for new token

src/main/webapp/app/components/SmallPageContainer.tsx, src/main/webapp/app/pages/userManagement/UserManagementPage.tsx
https://stackoverflow.com/questions/34438540/react-redux-super-agent-first-call-gets-terminated/36903428
=> First attempt to address the PUT network drops issue

src/main/webapp/app/pages/DataAccessPage.tsx
Signed-off-by: Hongxin Zhang <hongxin@cbio.mskcc.org>
=> update the text

src/main/webapp/app/components/Header.tsx, src/main/webapp/app/config/constants.ts, src/main/webapp/app/pages/menus/account.tsx
Fix https://github.com/oncokb/oncokb/issues/1824
=> Fix collapse issue

.yo-rc.json, k8s/oncokb-public-local.yml, mvnw, pom.xml, src/main/docker/app.yml, src/main/docker/redis.yml, src/main/java/org/mskcc/cbio/oncokb/config/ApplicationProperties.java, src/main/java/org/mskcc/cbio/oncokb/config/CacheConfiguration.java, src/main/java/org/mskcc/cbio/oncokb/config/MasterSlaveRedisCache.java, src/main/java/org/mskcc/cbio/oncokb/repository/CustomAuditEventRepository.java, src/main/resources/config/application-dev.yml, src/main/resources/config/application-prod.yml, src/main/resources/config/liquibase/master.xml, src/main/resources/logback-spring.xml, src/test/java/org/mskcc/cbio/oncokb/RedisTestContainerExtension.java, src/test/java/org/mskcc/cbio/oncokb/config/timezone/HibernateTimeZoneIT.java, src/test/java/org/mskcc/cbio/oncokb/repository/CustomAuditEventRepositoryIT.java, src/test/java/org/mskcc/cbio/oncokb/security/DomainUserDetailsServiceIT.java, src/test/java/org/mskcc/cbio/oncokb/service/AuditEventServiceIT.java, src/test/java/org/mskcc/cbio/oncokb/service/MailServiceIT.java, src/test/java/org/mskcc/cbio/oncokb/service/UserServiceIT.java, src/test/java/org/mskcc/cbio/oncokb/service/mapper/UserMapperIT.java, src/test/java/org/mskcc/cbio/oncokb/web/rest/AuditResourceIT.java, src/test/java/org/mskcc/cbio/oncokb/web/rest/ClientForwardControllerIT.java, src/test/java/org/mskcc/cbio/oncokb/web/rest/UserJWTControllerIT.java, src/test/java/org/mskcc/cbio/oncokb/web/rest/UserResourceIT.java, src/test/java/org/mskcc/cbio/oncokb/web/rest/errors/ExceptionTranslatorIT.java, src/test/resources/config/application.yml, src/test/resources/logback.xml
This solves https://github.com/oncokb/oncokb/issues/1729
=> Use master/slave server redis as caching 

src/main/webapp/app/pages/DataAccessPage.tsx
This interface will be updated to the following:
=> Improve the interface for downloading the data

.eslintrc.json, src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/genePage/GenePage.tsx, src/main/webapp/app/shared/utils/UrlUtils.tsx
Fix https://github.com/oncokb/oncokb/issues/1753
=> Show PMID links in gene background

src/main/java/org/mskcc/cbio/oncokb/OncokbApp.java, src/main/java/org/mskcc/cbio/oncokb/config/CacheConfiguration.java, src/main/java/org/mskcc/cbio/oncokb/config/ThymeleafConfig.java, src/main/java/org/mskcc/cbio/oncokb/config/application/ApplicationProperties.java, src/main/java/org/mskcc/cbio/oncokb/config/application/MasterSlaveRedisCache.java, src/main/java/org/mskcc/cbio/oncokb/config/application/RedisProperties.java, src/main/java/org/mskcc/cbio/oncokb/config/application/RedisType.java, src/main/java/org/mskcc/cbio/oncokb/config/application/SingleRedisCache.java, src/main/java/org/mskcc/cbio/oncokb/service/ApiProxyService.java, src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/ClientForwardController.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/SitemapResource.java, src/main/resources/config/application-dev.yml, src/main/resources/config/application-prod.yml
The use case is for the dev/prod set ups we should use different servers. It's really difficult to set up the master-slave in local development
=> Support both redis single server and master-slave server

src/main/webapp/app/components/login/LoginPage.tsx, src/main/webapp/app/store/AuthenticationStore.ts
This solves https://github.com/oncokb/oncokb/issues/1828
=> Add loading indicator after user clicks on Log in button

src/main/webapp/app/components/oncokbTable/OncoKBTable.tsx, src/main/webapp/app/pages/CancerGenesPage.tsx, src/main/webapp/app/pages/LevelOfEvidencePage.tsx, src/main/webapp/app/pages/userManagement/UserManagementPage.tsx
Fix https://github.com/oncokb/oncokb/issues/1841, https://github.com/oncokb/oncokb/issues/1844, oncokb/oncokb#1854
=> Fix users management and mobile display issue

src/main/java/org/mskcc/cbio/oncokb/config/application/ApplicationProperties.java, src/main/java/org/mskcc/cbio/oncokb/service/EmailService.java, src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java, src/main/resources/config/application-dev.yml, src/main/resources/config/application-prod.yml, src/main/webapp/app/components/account/ActivateAccount.tsx, src/main/webapp/app/shared/api/generated/API-docs.json, src/main/webapp/app/shared/api/generated/API.ts, src/main/webapp/app/shared/api/generated/OncoKbAPI-docs.json, src/main/webapp/app/shared/api/generated/OncoKbAPI.ts, src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI-docs.json, src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI.ts, src/test/java/org/mskcc/cbio/oncokb/web/rest/AccountResourceIT.java
For users in whitelist, they will see: 
For users are not, they will see:
=> Provide whitelist to automatically approve accounts

src/main/webapp/app/routes/routes.tsx
Fix https://github.com/oncokb/oncokb/issues/1831
=> Redirect to Home Page for 404 error

pom.xml, src/main/java/org/mskcc/cbio/oncokb/security/uuid/TokenProvider.java, src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java
This solves https://github.com/oncokb/oncokb/issues/1868
=> Minor updates

src/main/webapp/app/store/AnnotationStore.ts
This solves https://github.com/oncokb/oncokb/issues/1860
=> Use matched gene to for further api queries

package.json, src/main/webapp/app/store/AnnotationStore.ts
FIx https://github.com/oncokb/oncokb/issues/1881
=> Display all cbioportal mutations on mutation mapper

src/main/webapp/swagger-ui/index.html
Use `https://www.oncokb.org` to replace the proxy URL
FIx https://github.com/oncokb/oncokb/issues/1896
=> Temporary fix of swagger issue

package.json, src/main/webapp/app/pages/CancerGenesPage.tsx, src/main/webapp/app/pages/DataAccessPage.tsx, src/main/webapp/app/shared/api/generated/OncoKbAPI-docs.json, src/main/webapp/app/shared/api/generated/OncoKbAPI.ts, src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI-docs.json, src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI.ts, src/main/webapp/app/store/AppStore.ts, src/main/webapp/swagger-ui/index.html, yarn.lock
The previous version is wrong. The current version has been built on my local docker successfully.
=> Fixed OncoKB API issues

src/main/java/org/mskcc/cbio/oncokb/web/rest/ApiProxy.java
The GET will add 1 to token usage
The POST will add the number of items on the body list
This fixes https://github.com/oncokb/oncokb/issues/1887
=> Count the token usage based on the http request method

k8s/oncokb-public-local.yml, pom.xml, src/main/docker/app.yml, src/main/webapp/app/pages/AboutPage.tsx, src/main/webapp/app/pages/newsPage/NewsPage.tsx, src/main/webapp/app/pages/newsPage/NewsPageContent.tsx, src/main/webapp/swagger-ui/index.html
Fix https://github.com/oncokb/oncokb/issues/1909
=> Make data release on 02/12/2020

src/main/webapp/swagger-ui/index.html
This is related to https://github.com/oncokb/oncokb/issues/1909
=> Change 'Public APIs for Premium Users' to "Private APIs"

src/main/java/org/mskcc/cbio/oncokb/security/DomainUserDetailsService.java, src/main/java/org/mskcc/cbio/oncokb/security/UserNotApprovedException.java, src/main/java/org/mskcc/cbio/oncokb/service/EmailAlreadyUsedException.java, src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/service/UsernameAlreadyUsedException.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/errors/EmailAlreadyUsedException.java, src/main/webapp/app/components/login/LoginPage.tsx, src/main/webapp/app/pages/RegisterPage.tsx, src/main/webapp/app/shared/alert/ErrorAlert.tsx, src/main/webapp/app/store/AuthenticationStore.ts
This solves https://github.com/oncokb/oncokb/issues/1904
=> Give more informative message when user failed to login or register

src/main/webapp/app/pages/alterationPage/AlterationPage.tsx
This fixes https://github.com/oncokb/oncokb/issues/1951
=> Add more space between all summary sections in the gene page

src/main/webapp/app/shared/utils/Utils.tsx
This is related to https://github.com/oncokb/oncokb/issues/1949
=> Prevent  null exception when filtering content

src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/newsPage/NewsPage.tsx
This fixes https://github.com/oncokb/oncokb/issues/1946
=> Fix the linkout to register oncokb news

k8s/oncokb-public-local.yml, pom.xml, src/main/docker/app.yml, src/main/webapp/app/pages/genePage/GenePage.tsx
This is a bug, all gene types should be shown.
=> Show all available gene type

src/main/java/org/mskcc/cbio/oncokb/domain/enumeration/MailType.java
This fixes https://github.com/oncokb/oncokb/issues/1961
=> Do not send intake form for clarification email

.github/release-drafter.yml, k8s/oncokb-public-local.yml, pom.xml, src/main/docker/app.yml, src/main/webapp/app/config/constants.tsx, src/main/webapp/app/store/AnnotationStore.ts
This fixes https://github.com/oncokb/oncokb/issues/1966 and https://github.com/oncokb/oncokb/issues/1969
=> Use MSK overrides for mutation mapper

src/main/webapp/app/components/CitationTooltip.tsx, src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/alterationPage/AlterationPage.tsx, src/main/webapp/app/pages/genePage/GenePage.tsx
This fixes https://github.com/oncokb/oncokb/issues/1970
=> Add mutation effect references

src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java
This fixes https://github.com/oncokb/oncokb/issues/1976
=> Include the cc when sending intake form email

src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/ActionableGenesPage.tsx, src/main/webapp/app/pages/alterationPage/AlterationPage.tsx, src/main/webapp/app/pages/genePage/GenePage.tsx, src/main/webapp/app/shared/alert/UnknownGeneAlert.tsx, src/main/webapp/app/store/AnnotationStore.ts
This fixes https://github.com/oncokb/oncokb/issues/1972
=> Properly handle the rendering when queried gene does not exist

k8s/oncokb-public-local.yml, pom.xml, src/main/docker/app.yml, src/main/java/org/mskcc/cbio/oncokb/web/rest/ApiProxy.java
https://stackoverflow.com/questions/22877350/how-to-extract-ip-address-in-spring-mvc-controller-get-call
I forgot to record the ip if it's forwarded, and of course in the k8s, it's always the case.
This fixes https://github.com/oncokb/oncokb/issues/1980
=> Record the ip address when header has X-FORWARDED-FOR

src/main/webapp/app/config/theme.ts, src/main/webapp/app/pages/alterationPage/AlterationPage.tsx, src/main/webapp/app/shared/utils/Utils.tsx
This fixes https://github.com/oncokb/oncokb/issues/1988
=> Show a light grey color icon when the citations is not available

src/main/webapp/app/components/Header.tsx, src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/APIAccessPage.tsx, src/main/webapp/app/pages/newsPage/NewsPageContent.tsx, src/main/webapp/app/routes/routes.tsx, src/main/webapp/index.html
This fixes https://github.com/oncokb/oncokb/issues/2004
=> Change Data Access page to API Access

k8s/oncokb-public-local.yml, package.json, pom.xml, src/main/docker/app.yml, src/main/webapp/app/components/Header.tsx, src/main/webapp/app/components/userMessager/UserMessage.tsx, src/main/webapp/app/components/userMessager/styles.module.scss, src/main/webapp/app/layout.scss, yarn.lock
This fixes https://github.com/oncokb/oncokb/issues/2012
=> Include a global banner for personalized message

src/main/webapp/app/pages/HomePage.tsx, src/main/webapp/app/pages/TeamPage.tsx
- Removed David Hyman, MD
- Added Powered by ... in the main page
=> Update team page & main page

src/main/webapp/app/pages/alterationPage/AlterationPage.tsx, src/main/webapp/app/shared/utils/UrlUtils.tsx, src/main/webapp/app/shared/utils/Utils.tsx
This fixes https://github.com/oncokb/oncokb/issues/2025
=> Decode/Encode tumor type/alteration in the URL properly

src/main/webapp/app/components/Header.tsx, src/main/webapp/app/components/oncokbSearch/OncoKBSearch.tsx, src/main/webapp/app/pages/HomePage.tsx, src/main/webapp/app/pages/alterationPage/AlterationPage.tsx, src/main/webapp/app/pages/genePage/GenePage.tsx, src/main/webapp/app/shared/utils/Utils.tsx
This fixes https://github.com/oncokb/oncokb/issues/2015
=> Add search bar on the header

src/main/webapp/app/components/Header.tsx
This fixes https://github.com/oncokb/oncokb/issues/2039
=> Remove banner

src/main/java/org/mskcc/cbio/oncokb/config/CacheConfiguration.java, src/main/java/org/mskcc/cbio/oncokb/config/application/ApplicationProperties.java, src/main/java/org/mskcc/cbio/oncokb/config/application/EmailAddresses.java, src/main/java/org/mskcc/cbio/oncokb/repository/TokenRepository.java, src/main/java/org/mskcc/cbio/oncokb/security/uuid/TokenProvider.java, src/main/java/org/mskcc/cbio/oncokb/service/TokenService.java, src/main/java/org/mskcc/cbio/oncokb/service/impl/TokenServiceImpl.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/ApiProxy.java, src/main/resources/config/application-dev.yml, src/main/resources/config/application-prod.yml
This fixes https://github.com/oncokb/oncokb/issues/1908
=> Send email when public website token is used more than the threshold

src/main/java/org/mskcc/cbio/oncokb/domain/enumeration/MailType.java, src/main/java/org/mskcc/cbio/oncokb/repository/TokenRepository.java, src/main/java/org/mskcc/cbio/oncokb/security/AuthoritiesConstants.java, src/main/java/org/mskcc/cbio/oncokb/security/uuid/TokenProvider.java, src/main/java/org/mskcc/cbio/oncokb/service/AuditEventService.java, src/main/java/org/mskcc/cbio/oncokb/service/MailService.java, src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java, src/main/java/org/mskcc/cbio/oncokb/service/TokenService.java, src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/service/impl/TokenServiceImpl.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/MailsController.java, src/main/resources/i18n/messages.properties, src/main/resources/templates/mail/declareEmailOwnership.html, src/test/java/org/mskcc/cbio/oncokb/service/AuditEventServiceIT.java, src/test/java/org/mskcc/cbio/oncokb/service/UserServiceIT.java
This fixes https://github.com/oncokb/oncokb/issues/2058 and https://github.com/oncokb/oncokb/issues/2059
=> Send verification email before user account expires at 14/3 days marks

src/main/java/org/mskcc/cbio/oncokb/repository/TokenStatsRepository.java, src/main/java/org/mskcc/cbio/oncokb/service/AuditEventService.java, src/main/java/org/mskcc/cbio/oncokb/service/TokenStatsService.java, src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/service/impl/TokenStatsServiceImpl.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java, src/main/resources/config/application-prod.yml
This fixes https://github.com/oncokb/oncokb/issues/2062
=> Provide endpoints to delete old token status and old audit events

.github/workflows/sentry-release.yml, pom.xml, src/main/java/org/mskcc/cbio/oncokb/OncokbPublicApp.java, src/main/resources/config/application-dev.yml, src/main/resources/config/application-prod.yml, src/main/resources/config/application.yml
This is a part of fixes for https://github.com/oncokb/oncokb/issues/2031
=> Update sentry config

src/main/java/org/mskcc/cbio/oncokb/domain/enumeration/MailType.java, src/main/java/org/mskcc/cbio/oncokb/repository/UserMailsRepository.java, src/main/java/org/mskcc/cbio/oncokb/service/MailService.java, src/main/java/org/mskcc/cbio/oncokb/service/UserMailsService.java, src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java, src/main/resources/i18n/messages.properties, src/main/resources/templates/mail/verifyEmailBeforeAccountExpires.html
This fixes https://github.com/oncokb/oncokb/issues/2076
=> Prevent sending verification email multiple times

src/main/java/org/mskcc/cbio/oncokb/config/Constants.java, src/main/java/org/mskcc/cbio/oncokb/config/application/ApplicationProperties.java, src/main/java/org/mskcc/cbio/oncokb/domain/enumeration/MailType.java, src/main/java/org/mskcc/cbio/oncokb/service/MailService.java, src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java, src/main/resources/templates/mail/approvalMSKInCommercial.html
This fixes https://github.com/oncokb/oncokb/issues/2014
=> Approve MSK user who requests commercial license as Academic

.github/release-drafter.yml, k8s/oncokb-public-local.yml, pom.xml, src/main/docker/app.yml, src/main/resources/config/application-prod.yml
This fixes https://github.com/oncokb/oncokb/issues/2085
=> Change to smtp-relay service for better security

src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/newsPage/NewsList.tsx, src/main/webapp/app/pages/newsPage/NewsPage.tsx, src/main/webapp/app/pages/newsPage/NewsPageContent.tsx, src/main/webapp/app/pages/newsPage/UpdatedTxImplListItem.tsx, src/main/webapp/app/shared/utils/Utils.tsx
This fixes https://github.com/oncokb/oncokb/issues/2086
=> Include data version in the News page & Include News for data v2.4 release

src/main/webapp/app/pages/alterationPage/AlterationPage.tsx, src/main/webapp/app/shared/utils/Utils.tsx
This is related to https://github.com/oncokb/oncokb/issues/2091
=> Do not show Oncogenicity/MutationEffect/Citations for Oncogenic Mutations

src/main/resources/i18n/messages.properties, src/main/resources/templates/mail/verifyEmailBeforeAccountExpires.html, src/main/webapp/app/components/account/ActivateAccount.tsx, src/main/webapp/app/index.module.scss, src/main/webapp/app/variables.scss
This fixes https://github.com/oncokb/oncokb/issues/2094
=> Adjust messages related to account renewal

src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/SlackController.java
This is related to https://github.com/oncokb/oncokb/issues/2101
=> Always create a token when user account is approved

k8s/oncokb-public-local.yml, pom.xml, src/main/docker/app.yml, src/main/java/org/mskcc/cbio/oncokb/config/application/ApplicationProperties.java, src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java, src/main/resources/config/application-dev.yml, src/main/resources/config/application-prod.yml
This fixes https://github.com/oncokb/oncokb/issues/2102
=> Include licensed domains to differentiate the auto-response

src/main/webapp/app/components/newAccountForm/NewAccountForm.tsx, src/main/webapp/app/pages/CreateAccountPage.tsx, src/main/webapp/app/pages/RegisterPage.tsx
This fixes https://github.com/oncokb/oncokb/issues/2106
=> Make company section optional when admin creates an new account

src/main/java/org/mskcc/cbio/oncokb/config/SecurityConfiguration.java, src/main/java/org/mskcc/cbio/oncokb/security/UserNotApprovedException.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/errors/TokenExpiredException.java, src/main/webapp/app/components/login/LoginPage.tsx, src/main/webapp/app/pages/CreateAccountPage.tsx, src/main/webapp/app/pages/RegisterPage.tsx, src/main/webapp/app/shared/alert/ErrorAlert.tsx, src/main/webapp/app/shared/alert/ErrorAlertUtils.ts, src/main/webapp/app/shared/api/errorMessages.ts, src/main/webapp/app/shared/api/generated/API-docs.json, src/main/webapp/app/shared/api/generated/API.ts, src/main/webapp/app/store/AuthenticationStore.ts
This fixes https://github.com/oncokb/oncokb/issues/2090
=> Allow user to resend the verification email

src/main/java/org/mskcc/cbio/oncokb/config/CacheConfiguration.java, src/main/java/org/mskcc/cbio/oncokb/repository/TokenRepository.java, src/main/resources/config/application-prod.yml
This fixes https://github.com/oncokb/oncokb/issues/2095
=> Cache the token query to improve the performance

src/main/webapp/app/components/Header.tsx, src/main/webapp/app/components/userMessager/UserMessage.tsx, src/main/webapp/app/components/userMessager/styles.module.scss
This fixes https://github.com/oncokb/oncokb/issues/2105
=> Include webinar messages

src/main/webapp/app/pages/AboutPage.tsx
The URL will be ***.org/about#showTutorials=true
=> Include OncoKB API Webinar & Update URL when the tutorials modal is opened

src/main/java/org/mskcc/cbio/oncokb/service/UserService.java
This fixes https://github.com/oncokb/oncokb/issues/2112
=> Make sure a token is generated after account is approved/created

src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/UserResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/ManagedUserVM.java, src/main/webapp/app/components/newAccountForm/NewAccountForm.tsx, src/main/webapp/app/pages/CreateAccountPage.tsx, src/main/webapp/app/shared/api/generated/API-docs.json, src/main/webapp/app/shared/api/generated/API.ts, src/test/java/org/mskcc/cbio/oncokb/web/rest/AccountResourceIT.java
This fixes https://github.com/oncokb/oncokb/issues/2126
=> Specify account expiration days if is trial account when creating account by admin

k8s/oncokb-public-local.yml, pom.xml, src/main/docker/app.yml, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java
In this case, the MSK commercial user would not be approved automatically. The pr fixes this issue.
=> Fix the issue when MSK is in the account whitelist

src/main/java/org/mskcc/cbio/oncokb/security/uuid/TokenProvider.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/ClientForwardController.java, src/main/resources/config/application-prod.yml, src/main/webapp/app/components/userMessager/UserMessage.tsx, src/main/webapp/app/config/constants.tsx, src/main/webapp/app/index.tsx, src/main/webapp/app/indexUtils.tsx, src/main/webapp/app/store/AuthenticationStore.ts, src/main/webapp/index.html
This is an intend to solve https://github.com/oncokb/oncokb/issues/2129
=> Avoid infinity refresh loop

src/main/java/org/mskcc/cbio/oncokb/config/Constants.java, src/main/java/org/mskcc/cbio/oncokb/repository/TokenRepository.java, src/main/java/org/mskcc/cbio/oncokb/security/uuid/TokenProvider.java, src/main/java/org/mskcc/cbio/oncokb/service/TokenService.java, src/main/java/org/mskcc/cbio/oncokb/service/impl/TokenServiceImpl.java
This is an intent to solve https://github.com/oncokb/oncokb/issues/2129
=> For publicwebsite token fetch, avoid the cache

src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java
This fixes oncokb/oncokb#2111
This re-pull request for #470
=> Domain Check

src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java
This fixes https://github.com/oncokb/oncokb/issues/2132
=> Update token usage for the ones without any stats

README.md, src/main/webapp/app/config/constants.tsx, src/main/webapp/app/shared/api/clientInstance.ts, src/main/webapp/app/shared/api/oncokbClientInstance.ts, src/main/webapp/app/shared/api/oncokbPrivateClientInstance.ts, src/main/webapp/app/shared/utils/DevUtils.ts
This implements https://github.com/oncokb/oncokb/issues/2134
=> Using localStorage to set client api

src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/genePage/GenePage.tsx
- Change FDA-approved to FDA-approved drugs, this fixes oncokb/oncokb#2153
- Show gene background if no alteration curated, this fixes oncokb/oncokb#2151
- Do not show Mutation Mapper when entrez gene id is below 0, this fixes oncokb/oncokb#2155
=> Gene page improvement

src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/genePage/GenePage.module.scss, src/main/webapp/app/pages/genePage/GenePage.tsx, src/main/webapp/app/pages/genePage/ReferenceGenomeInfo.tsx, src/main/webapp/app/shared/api/generated/OncoKbAPI-docs.json, src/main/webapp/app/shared/api/generated/OncoKbAPI.ts, src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI-docs.json, src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI.ts
This fixes https://github.com/oncokb/oncokb/issues/2150
=> Show both grch37 and 38 isoform and refseq info on the gene page 

package.json, src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/ActionableGenesPage.tsx, src/main/webapp/app/pages/alterationPage/AlterationPage.tsx, src/main/webapp/app/pages/annotationPage/AlterationInfo.tsx, src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx, src/main/webapp/app/pages/genePage/GenePage.tsx, src/main/webapp/app/pages/genePage/ReferenceGenomeInfo.tsx, src/main/webapp/app/pages/hgvsgPage/HgvsgPage.tsx, src/main/webapp/app/routes/routes.tsx, src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI-docs.json, src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI.ts, src/main/webapp/app/shared/utils/Utils.tsx, src/main/webapp/app/store/AnnotationStore.ts, yarn.lock
This fixes https://github.com/oncokb/oncokb/issues/1410
=> Support hgvsg for variant page

k8s/oncokb-public-local.yml, pom.xml, src/main/docker/app.yml, src/main/webapp/app/components/searchOption/SearchOption.tsx, src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI-docs.json, src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI.ts
This is related to https://github.com/oncokb/oncokb/issues/2199
=> Show annotation when the queryType is TEXT

src/main/java/org/mskcc/cbio/oncokb/config/application/ApplicationProperties.java, src/main/java/org/mskcc/cbio/oncokb/config/application/FrontendProperties.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/ClientForwardController.java, src/main/resources/config/application-dev.yml, src/main/resources/config/application-prod.yml, src/main/webapp/app/appConfig.ts, src/main/webapp/app/config/constants.tsx, src/main/webapp/app/index.tsx, src/main/webapp/app/indexUtils.tsx, src/main/webapp/index.html
This fixes https://github.com/oncokb/oncokb/issues/1878
=> Read Google Analytics and Sentry ID from server

src/main/java/org/mskcc/cbio/oncokb/domain/enumeration/MailType.java, src/main/java/org/mskcc/cbio/oncokb/service/MailService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java, src/main/resources/templates/mail/trialAccountIsAboutToExpire.html, src/test/java/org/mskcc/cbio/oncokb/web/rest/AuditResourceIT.java
This fixes https://github.com/oncokb/oncokb/issues/2152
=> Send email when trial account expires in 3 days

k8s/oncokb-public-local.yml, pom.xml, src/main/docker/app.yml, src/main/webapp/app/components/MskimpactLink.tsx, src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/newsPage/NewsPage.tsx, src/main/webapp/app/pages/newsPage/NewsPageContent.tsx, src/main/webapp/app/shared/links/PMIDLink.tsx
The pubmed url has been changed to pubmed.ncbi.nlm.nih.gov
=> Include the news for 0828202 & Fix the PubMed link

src/main/java/org/mskcc/cbio/oncokb/web/rest/ClientForwardController.java, src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
This fixes https://github.com/oncokb/oncokb/issues/1853
=> Support dot in the url of /gene and /hgvsg

src/main/java/org/mskcc/cbio/oncokb/service/UserService.java
This fixes https://github.com/oncokb/oncokb/issues/2234
=> Generate token when user is approved from user management page

src/main/webapp/app/components/barChart/BarChart.tsx, src/main/webapp/app/config/constants.tsx
This fixes https://github.com/oncokb/oncokb/issues/2232
=> Update bar chart styles based on feedback

package.json, src/main/java/org/mskcc/cbio/oncokb/web/rest/TokenResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/UserResource.java, src/main/webapp/app/components/newAccountForm/NewAccountForm.tsx, src/main/webapp/app/components/tokenInputGroups/TokenInputGroups.tsx, src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/AccountPage.tsx, src/main/webapp/app/pages/account/AccountUtils.ts, src/main/webapp/app/pages/sendEmails/SendEmailsPage.tsx, src/main/webapp/app/pages/userManagement/UserDetailsPage.tsx, src/main/webapp/app/pages/userPage/UserPage.tsx, src/main/webapp/app/routes/routes.tsx, src/main/webapp/app/shared/api/generated/API-docs.json, src/main/webapp/app/shared/api/generated/API.ts, src/main/webapp/app/shared/table/EmailTable.tsx, src/main/webapp/app/variables.scss, yarn.lock
- Admin can update other users info
- Display tokens in the User Page
- Show email history
This fixes https://github.com/oncokb/oncokb/issues/2124
=> Add User Page

src/main/webapp/app/pages/ActionableGenesPage.tsx
The previous gene model change causes the issue.
=> Show correct alteration name in the actionable genes download file

src/main/webapp/app/pages/alterationPage/AlterationPage.tsx
This fixes https://github.com/oncokb/oncokb/issues/2231
=> Decode the tumor type query when it's changed

src/main/java/org/mskcc/cbio/oncokb/config/CacheConfiguration.java, src/main/java/org/mskcc/cbio/oncokb/config/cache/TokenCacheResolver.java, src/main/java/org/mskcc/cbio/oncokb/repository/TokenRepository.java, src/main/java/org/mskcc/cbio/oncokb/service/impl/TokenServiceImpl.java, src/main/webapp/app/components/calendarButton/CalendarButton.tsx, src/main/webapp/app/pages/userPage/UserPage.tsx
Component update to:
We also refetch the tokens after modifying so the new expiration date would be reflected.
This fixes https://github.com/oncokb/oncokb/issues/2246
=> Fix redis cache & Update token extension calendar component 

src/main/java/org/mskcc/cbio/oncokb/config/application/ApplicationProperties.java, src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java, src/main/resources/config/application-dev.yml, src/main/resources/config/application-prod.yml
The slack bot gives different message for trial account. And it will not be approved by others except the IT team.
=> Add support for trialed domain

pom.xml, src/main/java/org/mskcc/cbio/oncokb/config/application/AWSProperties.java, src/main/java/org/mskcc/cbio/oncokb/config/application/ApplicationProperties.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/UsageAnalysisController.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/UsageSummary.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/UserOverviewUsage.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/UserUsage.java, src/main/resources/config/application-dev.yml, src/main/resources/config/application-prod.yml, src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/AccountPage.tsx, src/main/webapp/app/pages/menus/account.tsx, src/main/webapp/app/pages/usageAnalysisPage/UsageAnalysisPage.tsx, src/main/webapp/app/pages/usageAnalysisPage/UsageDetailsTable.tsx, src/main/webapp/app/pages/usageAnalysisPage/UserUsagePage.tsx, src/main/webapp/app/routes/AdminRoutes.tsx, src/main/webapp/app/shared/api/generated/API.ts
This implements 
- https://github.com/oncokb/oncokb/issues/2273
- https://github.com/oncokb/oncokb/issues/2274
Some screenshots below:
=> Usage Analysis Page

src/main/java/org/mskcc/cbio/oncokb/web/rest/UsageAnalysisController.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/UserOverviewUsage.java, src/main/webapp/app/pages/usageAnalysisPage/UsageAnalysisPage.tsx, src/main/webapp/app/pages/usageAnalysisPage/UsageDetailsTable.tsx, src/main/webapp/app/pages/usageAnalysisPage/UserUsagePage.tsx, src/main/webapp/app/shared/api/generated/API.ts
This fixed https://github.com/oncokb/oncokb/issues/2303
=> oncokb usage page update

src/main/webapp/app/pages/CancerGenesPage.tsx
This fixes https://github.com/oncokb/oncokb/issues/2324
=> Update the cancer gene list references

src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/sendEmails/SendEmailsPage.tsx, src/main/webapp/app/pages/userManagement/UserDetailsPage.tsx, src/main/webapp/app/pages/userManagement/UserManagementPage.tsx
This fixes https://github.com/oncokb/oncokb/issues/2340
=> Increase the user size when pulling users information

src/main/webapp/app/components/Footer.tsx, src/main/webapp/app/pages/newsPage/NewsPageContent.tsx, src/main/webapp/app/shared/api/generated/OncoKbAPI-docs.json, src/main/webapp/app/shared/api/generated/OncoKbAPI.ts, src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI-docs.json, src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI.ts
OncoTree paper has been accepted. We need to update the website link to oncotree.info
=> Update OncoTree link

pom.xml, src/main/java/org/mskcc/cbio/oncokb/config/application/ApplicationProperties.java, src/main/java/org/mskcc/cbio/oncokb/domain/enumeration/MailType.java, src/main/java/org/mskcc/cbio/oncokb/security/uuid/TokenProvider.java, src/main/java/org/mskcc/cbio/oncokb/service/MailService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/ExposedToken.java, src/main/resources/config/application-dev.yml, src/main/resources/i18n/messages.properties, src/main/resources/templates/mail/activationEmail.html, src/main/resources/templates/mail/approvalEmail.html, src/main/resources/templates/mail/creationEmail.html, src/main/resources/templates/mail/licenseReview.html, src/main/resources/templates/mail/passwordResetEmail.html, src/main/resources/templates/mail/searchingResponseStructureHasChanged.html, src/main/resources/templates/mail/tokenHasBeenExposed.html, src/main/resources/templates/mail/tokenHasBeenExposedToUser.html
Implements https://github.com/oncokb/oncokb/issues/2298
=> Send email when token exposed

src/main/webapp/app/components/Header.tsx, src/main/webapp/app/config/constants.tsx, src/main/webapp/app/store/WindowStore.ts, src/main/webapp/app/variables.scss
Show MSK logo as much as possible
=> Adjust grid layout

src/main/webapp/app/pages/alterationPage/AlterationPage.module.scss, src/main/webapp/app/pages/annotationPage/AlterationInfo.tsx, src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx, src/main/webapp/app/pages/annotationPage/AnnotationPageTable.tsx, src/main/webapp/app/pages/genePage/GenePage.tsx, src/main/webapp/app/pages/genePage/GenePageTable.tsx
This implemented https://github.com/oncokb/oncokb/issues/2352
Mockup:
- Gene Page
- Variant Page
=> update genes page and variant page to show Dx/Px

src/main/webapp/app/App.tsx, src/main/webapp/app/Main.tsx, src/main/webapp/app/routes/routes.tsx, src/main/webapp/app/shared/auth/RecaptchaBoundaryRoute.tsx, src/main/webapp/app/store/WindowStore.ts
This implements https://github.com/oncokb/oncokb/issues/2361
Disable recaptcha on home page can reduce the possibility of showing challenge in incognito model.
=> update recaptcha - ignore home page

src/main/webapp/app/components/Footer.tsx, src/main/webapp/app/pages/ActionableGenesPage.tsx, src/main/webapp/app/pages/HomePage.tsx, src/main/webapp/app/pages/alterationPage/AlterationPage.tsx, src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx, src/main/webapp/app/pages/genePage/GenePage.tsx, src/main/webapp/app/pages/hgvsgPage/HgvsgPage.tsx, src/main/webapp/app/pages/newsPage/NewsPage.tsx, src/main/webapp/app/pages/newsPage/NewsPageContent.tsx, src/main/webapp/app/shared/icons/ExternalLinkIcon.tsx, src/main/webapp/app/shared/utils/UrlUtils.tsx, src/main/webapp/app/shared/utils/Utils.tsx, src/main/webapp/app/store/AnnotationStore.ts
This fixes https://github.com/oncokb/oncokb/issues/2367
=> Add OncoTree Linkout && Change Tumor Type to Cancer Type

src/main/resources/config/application.yml
This fixes https://github.com/oncokb/oncokb/issues/2350
=> Increase pageable max-page-size to 5000

src/main/webapp/app/pages/userPage/UserPage.tsx
This fixes https://github.com/oncokb/oncokb/issues/2351
=> Fix issue user authorities do not show in user details page

src/main/java/org/mskcc/cbio/oncokb/service/MailService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java, src/main/resources/templates/mail/tokenHasBeenExposed.html, src/main/resources/templates/mail/tokenHasBeenExposedToUser.html
This implemented https://github.com/oncokb/oncokb/issues/2362
=> Update response for Google/Baidu checking

src/main/webapp/app/pages/HomePage.tsx, src/main/webapp/app/pages/LevelOfEvidencePage.tsx, src/main/webapp/app/pages/genePage/GenePage.tsx, src/main/webapp/app/shared/utils/Utils.tsx
This fixed https://github.com/oncokb/oncokb/issues/2370
The reason of item one and item two in this issue is we set those pages' routes as private route in current instance.
=> Fix URL paramater bug

src/main/webapp/app/pages/actionableGenesPage/ActionableGenesPage.tsx, src/main/webapp/app/pages/actionableGenesPage/LevelSelectionRow.tsx
This fixed https://github.com/oncokb/oncokb/issues/2358
=> Fix actionable gene page child component status issue

src/main/webapp/app/pages/genePage/GenePage.tsx, src/main/webapp/app/shared/utils/ReactTableUtils.ts, src/main/webapp/app/shared/utils/Utils.tsx
This fixes https://github.com/oncokb/oncokb/issues/2376
=> Update the citations column default sorting method

src/main/java/org/mskcc/cbio/oncokb/service/UserService.java
This fixes https://github.com/oncokb/oncokb/issues/2375
=> Remove reset key valid time restriction

src/main/webapp/app/components/Footer.module.scss, src/main/webapp/app/index.scss
This fixed https://github.com/oncokb/oncokb/issues/2382
=> fix footer clicking bug

src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/UsageSummary.java, src/main/webapp/app/pages/usageAnalysisPage/UsageAnalysisPage.tsx, src/main/webapp/app/pages/usageAnalysisPage/UsageDetailsTable.tsx, src/main/webapp/app/pages/usageAnalysisPage/UserUsagePage.tsx, src/main/webapp/app/shared/api/generated/API-docs.json, src/main/webapp/app/shared/api/generated/API.ts
I believe these changes were caused by the recent usage analysis changes.
=> Update to the latest api client

src/main/webapp/app/components/account/AccountPassword.tsx, src/main/webapp/app/pages/RegisterPage.tsx
This fixes https://github.com/oncokb/oncokb/issues/2388
=> Use ErrorAltertUtils to handle OncoKBError

src/main/webapp/app/App.tsx, src/main/webapp/app/Main.tsx, src/main/webapp/app/routes/routes.tsx, src/main/webapp/app/shared/auth/RecaptchaBoundaryRoute.tsx, src/main/webapp/app/store/AppStore.ts, src/main/webapp/app/store/WindowStore.ts
This is to make sure the window click event would not trigger the recaptcha verification for logged in user
=> Move recaptcha logic to App and store a state in AppStore to share

src/main/webapp/app/shared/auth/RecaptchaBoundaryRoute.tsx
I'd like still keep the new routing until we figure another solution out.
=> Disable recaptcha verifying page

src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/actionableGenesPage/ActionableGenesPage.tsx, src/main/webapp/app/shared/utils/ReactTableUtils.ts
By the following order
1. Level
2. hugo symbol
3. alterations
4. cancer types
5. drugs
=> Sort actionable gene download file

src/main/java/org/mskcc/cbio/oncokb/querydomain/UserTokenUsageWithInfo.java, src/main/java/org/mskcc/cbio/oncokb/repository/TokenStatsRepository.java, src/main/java/org/mskcc/cbio/oncokb/service/S3Service.java, src/main/java/org/mskcc/cbio/oncokb/service/TokenStatsService.java, src/main/java/org/mskcc/cbio/oncokb/service/impl/TokenStatsServiceImpl.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/UsageAnalysisController.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/ResourceModel.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/UsageSummary.java
Implemented https://github.com/oncokb/oncokb/issues/2349
=> Implement user usage analysis pipeline

src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java, src/main/resources/templates/mail/approvalMSKInCommercial.html, src/main/resources/templates/mail/clarifyAcademicUseWithoutInstituteEmail.html, src/main/resources/templates/mail/clarifyLicenseInForProfileCompany.html, src/main/resources/templates/mail/licenseReview.html, src/main/resources/templates/mail/sendIntakeForm.html, src/main/resources/templates/mail/trialAccountIsAboutToExpire.html, src/main/resources/templates/mail/verifyEmailBeforeAccountExpires.html
Reverts oncokb/oncokb-public#610
=> Revert "Fix email template signature issue"

src/main/webapp/app/pages/HomePage.tsx, src/main/webapp/app/pages/annotationPage/AlterationInfo.tsx, src/main/webapp/app/pages/genePage/GenePage.tsx, src/main/webapp/app/pages/newsPage/ChangedAnnotatonListItem.tsx, src/main/webapp/app/pages/newsPage/NewsPageContent.tsx, src/main/webapp/app/pages/newsPage/UpdatedTxImplListItem.tsx, src/main/webapp/app/pages/newsPage/UpdatedTxImplOldFormatListItem.tsx, src/main/webapp/app/pages/teamPage/TeamPage.tsx
This fixes https://github.com/oncokb/oncokb/issues/2460
=> Improve mobile viewer experience

package.json, src/main/webapp/app/pages/genePage/GenePage.tsx, yarn.lock
This fixes https://github.com/oncokb/oncokb/issues/2482
=> Use filtered clinical alterations for Tx/Dx/Px tab

src/main/java/org/mskcc/cbio/oncokb/config/SecurityConfiguration.java, src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/KeyAndEmailVM.java, src/main/resources/config/application-dev.yml
This is related https://github.com/oncokb/oncokb/issues/2519
=> Add endpoint to finish trial account activation

src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java, src/main/webapp/app/components/tokenInputGroups/TokenInputGroups.tsx, src/main/webapp/app/components/userMessager/UserMessage.tsx, src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/AccountPage.tsx, src/main/webapp/app/pages/userPage/QuickToolButton.tsx, src/main/webapp/app/pages/userPage/TrialAccountModal.tsx, src/main/webapp/app/pages/userPage/UserPage.tsx, src/main/webapp/app/shared/api/generated/API-docs.json, src/main/webapp/app/shared/api/generated/API.ts, src/main/webapp/app/shared/button/CopyButton.tsx, src/main/webapp/app/store/WindowStore.ts
This fixes https://github.com/oncokb/oncokb/issues/2525
=> Add tool to initiate the trial account

src/main/webapp/app/shared/button/CopyButton.tsx
This fixes https://github.com/oncokb/oncokb/issues/2537
=> Only copy the text to clipboard when using CopyButton

src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/newsPage/NewsPage.tsx, src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
=> Update data v3.3 News

src/main/java/org/mskcc/cbio/oncokb/domain/enumeration/MailType.java, src/main/java/org/mskcc/cbio/oncokb/service/MailService.java, src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/SlackController.java, src/main/resources/i18n/messages.properties, src/main/resources/templates/mail/activateFreeTrial.html
This fixes https://github.com/oncokb/oncokb/issues/2569
=> Give admin option to give user trial access through slack

src/main/java/org/mskcc/cbio/oncokb/service/EmailService.java, src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java, src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/util/MainUtil.java, src/main/java/org/mskcc/cbio/oncokb/util/StringUtil.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/SlackController.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/slack/ActionId.java
In the new interface, admin can approve/give trial access/Change License/Update latest info of user
=> Update slack message to include more info/action

src/main/webapp/app/components/newAccountForm/NewAccountForm.tsx, src/main/webapp/app/pages/RegisterPage.tsx
This fixes https://github.com/oncokb/oncokb/issues/2571
=> Give option to show/hide registration sections

pom.xml, src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/SlackController.java
This fixes https://github.com/oncokb/oncokb/issues/2574
=> Include approval user info in the slack message

src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java
Only the approve button should be shown as primary
=> Update the slack buttons style

src/main/java/org/mskcc/cbio/oncokb/config/application/ApplicationProperties.java, src/main/java/org/mskcc/cbio/oncokb/config/application/SlackProperties.java, src/main/java/org/mskcc/cbio/oncokb/domain/UserIdMessagePair.java, src/main/java/org/mskcc/cbio/oncokb/domain/UserMessagePair.java, src/main/java/org/mskcc/cbio/oncokb/domain/enumeration/MailType.java, src/main/java/org/mskcc/cbio/oncokb/repository/UserRepository.java, src/main/java/org/mskcc/cbio/oncokb/service/MailService.java, src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java, src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/SlackController.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/slack/BlockId.java, src/main/resources/config/application-dev.yml, src/main/resources/config/application-prod.yml, src/main/resources/templates/fragments/tables.html, src/main/resources/templates/mail/listOfUnapprovedUsers.html, src/main/webapp/app/shared/api/generated/API-docs.json
* email list of unapproved users weekly, only include users that haven't been discussed
* added slack link and sort based on replies
* Add id for reach slack block
=> Send unapproved users weekly email

src/main/java/org/mskcc/cbio/oncokb/service/MailService.java, src/main/resources/templates/fragments/tables.html
- left align the header so the content of the column would be easier to be identified
- fix an issue when user does not have license attached. This happens in the test environment
=> Minor fixes

src/main/java/org/mskcc/cbio/oncokb/service/MailService.java, src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java, src/main/resources/templates/mail/listOfUnapprovedUsers.html
- Empty fields no longer show up as `**`
- If a list is empty the table will not show up in weekly email
=> Minor fixes to weekly email and slack integration

src/main/java/org/mskcc/cbio/oncokb/service/MailService.java
this fixes https://github.com/oncokb/oncokb/issues/2652
=> Change unapproved users email to license address

src/main/webapp/app/components/newAccountForm/NewAccountForm.tsx, src/main/webapp/app/pages/account/AccountUtils.ts
this fixes https://github.com/oncokb/oncokb/issues/2653
=> Stricter requirements to register for OncoKB account

src/main/webapp/app/pages/actionableGenesPage/ActionableGenesPage.tsx
This fixes https://github.com/oncokb/oncokb/issues/2674
=> Remove Drugs column when no Tx level is selcted

README.md, src/main/webapp/app/components/CitationTooltip.tsx, src/main/webapp/app/components/HomePageNumber.tsx, src/main/webapp/app/components/highlightLinkButton/HighlightLinkButton.module.scss, src/main/webapp/app/components/levelButton/LevelButton.tsx, src/main/webapp/app/components/loadingIndicator/LoadingIndicator.tsx, src/main/webapp/app/components/loadingIndicator/styles.module.scss, src/main/webapp/app/pages/HomePage.tsx, src/main/webapp/app/pages/actionableGenesPage/ActionableGenesPage.tsx, src/main/webapp/app/pages/alterationPage/AlterationPage.tsx, src/main/webapp/app/pages/genePage/GenePage.tsx, src/main/webapp/app/pages/hgvsgPage/HgvsgPage.tsx, src/main/webapp/app/pages/sendEmails/SendEmailsPage.tsx, src/main/webapp/app/pages/userManagement/UserDetailsPage.tsx, src/main/webapp/app/shared/button/LoadingButton.tsx
This fixes https://github.com/oncokb/oncokb/issues/2663
=> Add loading gif for the numbers on the main page

pom.xml, src/main/java/org/mskcc/cbio/oncokb/OncokbPublicApp.java, src/main/java/org/mskcc/cbio/oncokb/aop/logging/LoggingAspect.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/ApiProxy.java, src/main/resources/config/application-dev.yml, src/main/resources/config/application-prod.yml, src/main/resources/config/application.yml
This fixes https://github.com/oncokb/oncokb/issues/2665
=> Upgrade to sentry v5 & Do not send certain exceptions to Sentry

src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/newsPage/NewsPage.tsx, src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
This relates to https://github.com/oncokb/oncokb/issues/2680
Signed-off-by: Hongxin <5400599+zhx828@users.noreply.github.com>
=> Update news for data v3.6

src/main/webapp/app/pages/actionableGenesPage/ActionableGenesPage.tsx, src/main/webapp/app/pages/alterationPage/AlterationPage.tsx, src/main/webapp/app/pages/genePage/GenePage.tsx, src/main/webapp/app/pages/hgvsgPage/HgvsgPage.tsx, src/main/webapp/app/shared/route/types.tsx
- Fix issue that the FDA popup dose not show up properly
- Open Tx section when FDA section is folded and no other sections are open
- Support tab key in the hgvsg page path hash
This fixes https://github.com/oncokb/oncokb/issues/2693
=> Update features related to FDA content

jhipster-jdl.jh
Updated existing entities/enumerations in jdl file
Added Company entity
=> Update JDL file

src/main/webapp/app/shared/utils/Utils.tsx
This fixes https://github.com/oncokb/oncokb/issues/2704
=> Update FDA icons

src/main/java/org/mskcc/cbio/oncokb/config/SecurityConfiguration.java, src/main/java/org/mskcc/cbio/oncokb/domain/enumeration/CompanyType.java, src/main/java/org/mskcc/cbio/oncokb/service/CompanyService.java, src/main/java/org/mskcc/cbio/oncokb/service/impl/CompanyServiceImpl.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/CompanyDomainResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/CompanyResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/CompanyVM.java, src/main/webapp/app/components/newCompanyForm/NewCompanyForm.tsx, src/main/webapp/app/components/newCompanyForm/styles.module.scss, src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/CreateCompanyPage.tsx, src/main/webapp/app/pages/menus/account.tsx, src/main/webapp/app/routes/AdminRoutes.tsx, src/main/webapp/app/shared/api/generated/API-docs.json, src/main/webapp/app/shared/api/generated/API.ts, src/main/webapp/app/shared/select/FormSelectWithLabelField.tsx, src/main/webapp/app/shared/textarea/FormTextAreaField.tsx
This fixes [issue #2696](https://github.com/oncokb/oncokb/issues/2696)
- Created a route `/admin/create-company` that includes a form to add a new company
- Company and CompanyDomain related API calls are only available to admins
- Created `companyVM`  to send company information + domains to the backend.
=> Initial add company page

src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/service/dto/useradditionalinfo/Activation.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/UserResource.java, src/main/webapp/app/pages/userPage/TrialAccountModal.tsx, src/main/webapp/app/pages/userPage/UserPage.tsx, src/main/webapp/app/shared/api/generated/API-docs.json, src/main/webapp/app/shared/api/generated/API.ts
This fixes https://github.com/oncokb/oncokb/issues/2742
=> Add whom initiated trial

src/main/webapp/app/pages/annotationPage/AlterationTableTabs.tsx, src/main/webapp/app/pages/genePage/GenePage.tsx, src/main/webapp/app/store/AnnotationStore.ts
This fixes https://github.com/oncokb/oncokb/issues/2738
=> Fix issue that gene tables cannot be searched

src/main/java/org/mskcc/cbio/oncokb/web/rest/TokenResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/TokenStatsResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/UserResource.java
- the  x- prefixed headers have been separated for a long time
- this, for some reasons, affects the response when update data models
This fixes https://github.com/oncokb/oncokb/issues/2685, https://github.com/oncokb/oncokb/issues/2736  and https://github.com/oncokb/oncokb/issues/2245
=> Do not return custom headers

src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java, src/main/webapp/app/pages/userPage/UserPage.tsx, src/main/webapp/app/shared/api/generated/API-docs.json, src/main/webapp/app/shared/api/generated/API.ts
We should try to avoid using email to identify users
=> Use login in most of the api calls

src/main/java/org/mskcc/cbio/oncokb/repository/UserDetailsRepository.java, src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/service/impl/CompanyServiceImpl.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/CompanyResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/UserResource.java, src/main/webapp/app/components/LicenseSelection.tsx, src/main/webapp/app/components/newCompanyForm/NewCompanyForm.tsx, src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/AccountPage.tsx, src/main/webapp/app/pages/CreateCompanyPage.tsx, src/main/webapp/app/pages/companyManagement/CompanyDetailsPage.module.scss, src/main/webapp/app/pages/companyManagement/CompanyDetailsPage.tsx, src/main/webapp/app/pages/companyPage/CompanyPage.tsx, src/main/webapp/app/pages/menus/account.tsx, src/main/webapp/app/pages/userManagement/UserDetailsPage.tsx, src/main/webapp/app/pages/userPage/UserPage.tsx, src/main/webapp/app/routes/AdminRoutes.tsx, src/main/webapp/app/routes/routes.tsx, src/main/webapp/app/shared/api/generated/API-docs.json, src/main/webapp/app/shared/api/generated/API.ts, src/main/webapp/app/shared/button/PillButton.scss, src/main/webapp/app/shared/button/PillButton.tsx, src/main/webapp/app/shared/list/FormListField.tsx, src/main/webapp/app/shared/list/styles.module.scss, src/main/webapp/app/shared/select/FormSelectWithLabelField.tsx, src/main/webapp/app/shared/table/UserTable.tsx, src/main/webapp/app/shared/textarea/FormTextAreaField.tsx
This is related to:  [issue #2695](https://github.com/oncokb/oncokb/issues/2695)
Depends on [company logic PR](https://github.com/oncokb/oncokb-public/pull/730)
=> View and Update Company Pages

src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/actionableGenesPage/ActionableGenesPage.tsx, src/main/webapp/app/pages/alterationPage/AlterationPage.tsx, src/main/webapp/app/pages/annotationPage/AlterationTableTabs.tsx, src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx, src/main/webapp/app/pages/genePage/GenePage.tsx, src/main/webapp/app/pages/hgvsgPage/HgvsgPage.tsx, src/main/webapp/app/shared/utils/UrlUtils.tsx, src/main/webapp/app/shared/utils/Utils.tsx, src/main/webapp/app/store/AnnotationStore.ts
This fixes [#2783 ](https://github.com/oncokb/oncokb/issues/2783)
=> Show protein change when the name is differ from it

src/main/java/org/mskcc/cbio/oncokb/config/CacheConfiguration.java, src/main/java/org/mskcc/cbio/oncokb/config/cache/CompanyCacheResolver.java, src/main/java/org/mskcc/cbio/oncokb/repository/CompanyRepository.java, src/main/java/org/mskcc/cbio/oncokb/service/impl/CompanyServiceImpl.java
This fixes [issue #2785](https://github.com/oncokb/oncokb/issues/2785)
This requires the `add-company-dropdown` pr
- Add a `companyCacheResolver` 
- Clear company caches when company is updated
=> Cache Companies

src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/aboutGroup/FdaRecognitionPage.tsx, src/main/webapp/app/pages/newsPage/NewlyAddedGenesListItem.tsx, src/main/webapp/app/pages/newsPage/NewsList.tsx, src/main/webapp/app/pages/newsPage/NewsPage.tsx, src/main/webapp/app/pages/newsPage/NewsPageContent.tsx, src/main/webapp/app/shared/utils/UrlUtils.tsx
This is related to https://github.com/oncokb/oncokb/issues/2800
=> Update news for data v3.9

src/main/java/org/mskcc/cbio/oncokb/aop/api/APIConditionallyEnabled.java, src/main/java/org/mskcc/cbio/oncokb/aop/api/APIConditionallyEnabledAspect.java, src/main/java/org/mskcc/cbio/oncokb/config/application/ApplicationProperties.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/ClientForwardController.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/UserResource.java, src/main/resources/config/application-dev.yml, src/main/resources/config/application-prod.yml, src/main/webapp/app/appConfig.ts, src/main/webapp/app/components/ReadonlyContent.tsx, src/main/webapp/app/components/account/PasswordResetInit.tsx, src/main/webapp/app/pages/CreateAccountPage.tsx, src/main/webapp/app/pages/RegisterPage.tsx, src/main/webapp/index.html
This is related to the [disable registration ticket](https://github.com/oncokb/oncokb/issues/2792)
- Created a `DisableEndpoint`  aop annotation that will send back `HttpStatus.Forbidden` to denote that the endpoint is disabled. 
- Reference: https://www.baeldung.com/spring-aop-annotation
- Show an alert message on frontend
- Added property to set application to readonly mode.
=> Disable User Registration

.jhipster/Company.json, jhipster-jdl.jdl, src/main/java/org/mskcc/cbio/oncokb/domain/Company.java, src/main/java/org/mskcc/cbio/oncokb/domain/enumeration/LicenseModel.java, src/main/java/org/mskcc/cbio/oncokb/service/CompanyService.java, src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/service/dto/CompanyDTO.java, src/main/java/org/mskcc/cbio/oncokb/service/impl/CompanyDomainServiceImpl.java, src/main/java/org/mskcc/cbio/oncokb/service/impl/CompanyServiceImpl.java, src/main/java/org/mskcc/cbio/oncokb/service/mapper/CompanyMapper.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/CompanyResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/SlackController.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/VerifyCompanyNameVM.java, src/main/webapp/app/components/newAccountForm/NewAccountForm.tsx, src/main/webapp/app/components/newCompanyForm/NewCompanyForm.tsx, src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/companyManagement/CompanyDetailsPage.tsx, src/main/webapp/app/pages/companyPage/CompanyPage.tsx, src/main/webapp/app/pages/userPage/UserPage.tsx, src/main/webapp/app/shared/api/generated/API-docs.json, src/main/webapp/app/shared/api/generated/API.ts, src/main/webapp/app/shared/table/UserTable.tsx, src/main/webapp/app/shared/utils/FormValidationUtils.tsx, src/test/java/org/mskcc/cbio/oncokb/service/CompanyServiceIT.java, src/test/java/org/mskcc/cbio/oncokb/service/UserServiceIT.java, src/test/java/org/mskcc/cbio/oncokb/service/mapper/CompanyMapperTest.java, src/test/java/org/mskcc/cbio/oncokb/web/rest/CompanyResourceIT.java, src/test/java/org/mskcc/cbio/oncokb/web/rest/UserResourceIT.java
This is related to [issue #2713](https://github.com/oncokb/oncokb/issues/2713)
Added tests for company service and updated some existing tests that were failing with new updates.
Minor fixes
- Can still add more test and edit current ones if needed.
=> Add Company Tests

src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java
This is related to [issue # 2809](https://github.com/oncokb/oncokb/issues/2809)
- Add an additional check to see if the user activated their trial yet (`activationDate != null`)
=> Show trial expiration date only when the trial is activated by user

src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java
The google result is often inaccurate/unverifiable. Baidu search never worked.
=> Do not check token in google/baidu

src/main/webapp/app/components/feedback/FeedbackForm.tsx, src/main/webapp/app/components/oncokbSearch/OncoKBSearch.tsx
This fixes [issue 2905](https://github.com/oncokb/oncokb/issues/2905)
- Email and Name are now required in the feedback form
- Allows us to address the feedback
=> Require email and name in feedback form

src/main/webapp/app/store/AnnotationStore.ts
This fixes https://github.com/oncokb/oncokb/issues/2909
=> Use exact alt/name for matchedAlteration

package.json, src/main/webapp/app/components/oncokbSearch/OncoKBSearch.tsx, yarn.lock
This fixes https://github.com/oncokb/oncokb/issues/2882
=> Update sentry-react & Fix error when async react-select options failed

src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java
Based on the rate limitation, we can only do 30 queries per minute. https://docs.github.com/en/rest/reference/rate-limit
This fixes https://github.com/oncokb/oncokb/issues/2784
=> Extend the timeout for reach github search query

pom.xml, src/main/java/org/mskcc/cbio/oncokb/config/CacheConfiguration.java, src/main/java/org/mskcc/cbio/oncokb/config/RateLimitConfiguration.java, src/main/java/org/mskcc/cbio/oncokb/config/SecurityConfiguration.java, src/main/java/org/mskcc/cbio/oncokb/config/cache/Buckert4jProxyManager.java, src/main/java/org/mskcc/cbio/oncokb/config/interceptor/RateLimitInterceptor.java, src/main/java/org/mskcc/cbio/oncokb/service/RateLimitService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/TokenResource.java, src/main/webapp/app/shared/api/generated/API-docs.json, src/main/webapp/app/shared/api/generated/API.ts, src/test/java/org/mskcc/cbio/oncokb/web/rest/TokenResourceIT.java
This fixes https://github.com/oncokb/oncokb/issues/2891
=> Support rate limiting on specific endpoint using ip address & Update token resource endpoints

src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/test/java/org/mskcc/cbio/oncokb/service/UserServiceIT.java
This fixes https://github.com/oncokb/oncokb/issues/2977
=> Allow user to initiate password resetting as long as the user exists in the database

src/main/resources/templates/mail/verifyEmailBeforeAccountExpires.html
This fixes https://github.com/oncokb/oncokb/issues/3003
=> Add login to verifyEmailBeforeAccountExpires email

screenshot-test/App.screenshot.js, src/main/webapp/app/App.tsx
The tool becomes so aggressive, even after validating, it keeps showing up on every page redirect.
=> Disable recaptcha

.github/release-drafter.yml, src/main/java/org/mskcc/cbio/oncokb/OncokbPublicApp.java
This fixes https://github.com/oncokb/oncokb/issues/3059 and https://github.com/oncokb/oncokb/issues/3060
=> Ignore sentry exceptions

pom.xml, src/main/java/org/mskcc/cbio/oncokb/config/application/ApplicationProperties.java, src/main/java/org/mskcc/cbio/oncokb/config/application/SmartsheetProperties.java, src/main/java/org/mskcc/cbio/oncokb/service/MailService.java, src/main/java/org/mskcc/cbio/oncokb/service/SmartsheetService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java, src/main/resources/config/application-dev.yml, src/main/resources/config/application-prod.yml
This fixes https://github.com/oncokb/oncokb/issues/2676
=> Add new user to ROC smartsheet after user verified their email

src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java
This fixes issue that email template cannot be fetched in production when path changes.
This fixes https://github.com/oncokb/oncokb/issues/3079
=> Use class loader to fetch file under the resource folder

src/main/resources/config/application-prod.yml
For other props that without value, they are considered as optional variable, and then should not be included.
This is related to https://github.com/oncokb/oncokb/issues/3099
=> Prod yaml prop file should only include ones with value

src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java, src/main/java/org/mskcc/cbio/oncokb/service/SmartsheetService.java, src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/UserResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/ManagedUserVM.java, src/main/webapp/app/pages/CreateCompanyUsersPage.tsx, src/main/webapp/app/shared/api/generated/API-docs.json, src/main/webapp/app/shared/api/generated/API.ts
- Do not send MSK users to the sheet
- For users created by the admin, these accounts need to be sent to ROC sheet.
- Do not send user that we sent academic email clarification to the sheet
- Give option to opt-out ROC review on user creation page
This fixes to https://github.com/oncokb/oncokb/issues/3088
=> Updates to smartsheet integration

src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
Restructure the news to make it easier to understand
=> Update news for data v3.13

src/main/java/org/mskcc/cbio/oncokb/domain/enumeration/MailType.java, src/main/java/org/mskcc/cbio/oncokb/service/MailService.java, src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/SlackController.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/slack/ActionId.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/slack/BlockId.java, src/main/resources/templates/mail/clarifyRegistrationInfo.html, src/main/resources/templates/mail/clarifyRegistrationInfoString.txt
This fixes https://github.com/oncokb/oncokb/issues/3113
=> Add slack option to ask user provide more registration info

src/main/java/org/mskcc/cbio/oncokb/repository/TokenRepository.java, src/main/java/org/mskcc/cbio/oncokb/repository/TokenStatsRepository.java, src/main/java/org/mskcc/cbio/oncokb/repository/UserDetailsRepository.java, src/main/java/org/mskcc/cbio/oncokb/repository/UserMailsRepository.java, src/main/java/org/mskcc/cbio/oncokb/service/AuditEventService.java, src/main/java/org/mskcc/cbio/oncokb/service/TokenService.java, src/main/java/org/mskcc/cbio/oncokb/service/TokenStatsService.java, src/main/java/org/mskcc/cbio/oncokb/service/UserDetailsService.java, src/main/java/org/mskcc/cbio/oncokb/service/UserMailsService.java, src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/service/impl/TokenServiceImpl.java, src/main/java/org/mskcc/cbio/oncokb/service/impl/TokenStatsServiceImpl.java, src/main/java/org/mskcc/cbio/oncokb/service/impl/UserDetailsServiceImpl.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/UserResource.java, src/main/webapp/app/pages/userPage/UserPage.tsx
We will delete all information related to the user, includes the following
- user mails
- tokens
- token stats
- user details
This fixes https://github.com/oncokb/oncokb/issues/2098
The following section will be added to the user page.
=> Allow admin to fully delete the user

src/main/java/org/mskcc/cbio/oncokb/domain/enumeration/MailType.java, src/main/java/org/mskcc/cbio/oncokb/service/MailService.java, src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/SlackController.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/slack/ActionId.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/slack/BlockId.java, src/main/resources/config/application-dev.yml, src/main/resources/i18n/messages.properties, src/main/resources/templates/mail/licenseOptions.html, src/main/resources/templates/mail/licenseOptions.txt
this fixes https://github.com/oncokb/oncokb-pipeline/issues/55
=> Add license options email to slack integration

src/main/java/org/mskcc/cbio/oncokb/service/UserService.java
Expires token immediately when user is inactivated from user details page. This fixes https://github.com/oncokb/oncokb/issues/3221
=> Expires token when user is inactivated

src/main/java/org/mskcc/cbio/oncokb/OncokbPublicApp.java
This fixes https://github.com/oncokb/oncokb/issues/3223
=> Disable traces sampling

src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/UsageAnalysisController.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/UsageSummary.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/UserOverviewUsage.java
The size of int no longer fits the actual usage. This fixes https://github.com/oncokb/oncokb/issues/3255
=> Use long instead of int in data usage models

src/main/webapp/app/shared/dropdown/CancerTypeSelect.tsx
This fixes https://github.com/oncokb/oncokb/issues/3256
=> Show All Solid/Liquid Tumors in the actionable genes page

src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/newsPage/NewlyAddedGenesListItem.tsx, src/main/webapp/app/pages/newsPage/NewsPage.tsx
This is related to https://github.com/oncokb/oncokb/issues/3310
=> Update news for 3.18 data release

src/main/java/org/mskcc/cbio/oncokb/config/Constants.java, src/main/java/org/mskcc/cbio/oncokb/security/uuid/TokenProvider.java, src/main/java/org/mskcc/cbio/oncokb/service/CompanyService.java, src/main/java/org/mskcc/cbio/oncokb/service/UserDetailsService.java, src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/service/impl/UserDetailsServiceImpl.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java, src/test/java/org/mskcc/cbio/oncokb/service/CompanyServiceIT.java, src/test/java/org/mskcc/cbio/oncokb/service/UserServiceIT.java
This fixes https://github.com/oncokb/oncokb/issues/3309
=> Add tests to govern user/token status changes after being associated with trial company

src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/test/java/org/mskcc/cbio/oncokb/service/UserServiceIT.java
This fixes https://github.com/oncokb/oncokb/issues/3318
=> Delete activation/reset key when activating/inactivating user

src/main/webapp/app/pages/userPage/TrialAccountModal.tsx, src/main/webapp/app/pages/userPage/UserPage.tsx
On the server side, there is no reinitiate concept. If user has trial initiated, nothing will be done if you click the reinitiate button.
=> Remove reinitiate trial concept

src/main/webapp/app/shared/utils/Utils.tsx
This fixes https://github.com/oncokb/oncokb/issues/3341
=> Include resistance in the Oncogenic Mutations definition

src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/newsPage/NewsPage.tsx, src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
This is related to https://github.com/oncokb/oncokb/issues/3382
=> Updates new for v4.1 

src/main/java/org/mskcc/cbio/oncokb/config/application/FrontendProperties.java, src/main/resources/config/application-dev.yml, src/main/resources/config/application-prod.yml, src/main/webapp/app/appConfig.ts, src/main/webapp/app/components/Header.tsx, src/main/webapp/app/components/login/LoginPage.tsx, src/main/webapp/app/shared/auth/private-route.tsx, src/main/webapp/index.html
This fixes https://github.com/oncokb/oncokb/issues/3373
=> Allow enable/disable authentication in the frontend

src/main/java/org/mskcc/cbio/oncokb/service/dto/UserDTO.java, src/main/webapp/app/pages/userPage/UserPage.tsx
This fixes https://github.com/oncokb/oncokb/issues/3352
=> Fix batch create

screenshot-test/App.screenshot.js, src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/UserResource.java, src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/sendEmails/SendEmailsPage.tsx, src/main/webapp/app/pages/userManagement/UserDetailsPage.tsx, src/main/webapp/app/shared/api/generated/API-docs.json, src/main/webapp/app/shared/api/generated/API.ts, src/test/java/org/mskcc/cbio/oncokb/web/rest/UserResourceIT.java
This fixes https://github.com/oncokb/oncokb/issues/3361
=> Without paging all managed users

src/main/webapp/app/App.tsx, src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/AboutPage.tsx, src/main/webapp/app/pages/CancerGenesPage.tsx, src/main/webapp/app/pages/FAQPage.tsx, src/main/webapp/app/pages/LevelOfEvidencePage.tsx, src/main/webapp/app/pages/aboutGroup/AboutPageNavTab.tsx, src/main/webapp/app/pages/aboutGroup/FdaRecognitionPage.tsx, src/main/webapp/app/pages/actionableGenesPage/ActionableGenesPage.tsx, src/main/webapp/app/pages/alterationPage/AlterationPage.tsx, src/main/webapp/app/pages/apiAccessGroup/APIAccessPage.tsx, src/main/webapp/app/pages/apiAccessGroup/TermsPage.tsx, src/main/webapp/app/pages/companyPage/CompanyPage.tsx, src/main/webapp/app/pages/genePage/GenePage.tsx, src/main/webapp/app/pages/hgvsgPage/HgvsgPage.tsx, src/main/webapp/app/pages/newsPage/NewsPage.tsx, src/main/webapp/app/pages/teamPage/TeamPage.tsx, src/main/webapp/app/pages/userPage/UserPage.tsx, src/main/webapp/app/pages/yearEndSummaryPage/YearEndSummaryPage.tsx, src/main/webapp/app/shared/utils/Utils.tsx
This is related to https://github.com/oncokb/oncokb/issues/3408
=> Update page titles to include OncoKB and MSKCC post fixes

src/main/webapp/app/oncokb-frontend-commons/src/components/LongText.tsx, src/main/webapp/app/pages/annotationPage/AlterationTableTabs.tsx, src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx
- Include drug description column and shorten the text by number of words
- Include cancer type in the page header
=> Include drug description column and shorten the text by number of words

src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
This fixes https://github.com/oncokb/oncokb/issues/3449
=> Update FDA partial recognition link in the News

package.json, src/main/webapp/app/App.tsx, src/main/webapp/index.html, yarn.lock
This fixes https://github.com/oncokb/oncokb/issues/3412
=> Upgrade to google analytics 4

src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx, src/main/webapp/app/shared/utils/UrlUtils.tsx, src/main/webapp/app/store/AnnotationStore.ts
This fixes https://github.com/oncokb/oncokb/issues/3507
=> Generate alteration names based on wether to show diff from alteration and name

src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/newsPage/NewsPage.tsx, src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
This is related to https://github.com/oncokb/oncokb/issues/3505
=> Updates news for v4.7

package.json, src/main/webapp/app/index.tsx, yarn.lock
This is related to https://github.com/oncokb/oncokb/issues/3547
=> Upgrade sentry/react to 7.72 and enable error reply

src/main/webapp/app/config/constants.tsx, src/main/webapp/app/routes/routes.tsx
This fixes https://github.com/oncokb/oncokb/issues/3571
=> Add hash and search when redirecting from legacy actionable genes page

src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/genePage/GenePage.tsx, src/main/webapp/app/shared/utils/UrlUtils.tsx
This fixes https://github.com/oncokb/oncokb/issues/3590
=> Replace CitationLink with SummaryWithRefs

src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/test/java/org/mskcc/cbio/oncokb/service/UserServiceIT.java
Fix https://github.com/oncokb/oncokb-pipeline/issues/191
=> Fix check duplicate users

src/main/java/org/mskcc/cbio/oncokb/config/Swagger2Config.java, src/main/java/org/mskcc/cbio/oncokb/config/application/ApplicationProperties.java, src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/errors/ErrorConstants.java, src/main/resources/config/application-dev.yml, src/main/resources/config/application-prod.yml, src/main/webapp/app/pages/apiAccessGroup/APIAccessPage.tsx
This fixes https://github.com/oncokb/oncokb/issues/3592
=> Allow configuring app base URL

src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/test/java/org/mskcc/cbio/oncokb/service/UserServiceIT.java, src/test/java/org/mskcc/cbio/oncokb/web/rest/SlackControllerIT.java
resolves https://github.com/oncokb/oncokb-pipeline/issues/206
=> Update duplicate user weighting

src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/SlackController.java, src/main/webapp/app/pages/userPage/UserPage.tsx
Quick fix allowing ROLE_API to be removed while maintaining requested status in DB
=> Do not update API requested after approval && Add title for API request justification in slack

src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java
resolves https://github.com/oncokb/oncokb-pipeline/issues/219
=> create activation key before sending email

src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java
resolves https://github.com/oncokb/oncokb-pipeline/issues/216
=> Allow admin to delete any token

src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/CompanyResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/SlackController.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/UserResource.java
resolves https://github.com/oncokb/oncokb/issues/3650
=> add role api to trial accounts

src/main/java/org/mskcc/cbio/oncokb/service/SentryService.java, src/main/java/org/mskcc/cbio/oncokb/service/SmartsheetService.java
This is related to https://github.com/oncokb/oncokb-pipeline/issues/231
=> Capture smartsheet exception more granularly && Add sentry service to capture exception or message

src/main/webapp/app/config/constants.tsx, src/main/webapp/app/shared/utils/UrlUtils.tsx, src/main/webapp/app/shared/utils/Utils.tsx
This will trim all additional info after the categorical alteration
=> Linkout to categorical alteration page if the alteration starts with the categorical alteration

src/main/java/org/mskcc/cbio/oncokb/config/SecurityConfiguration.java
This fixes https://github.com/oncokb/oncokb-pipeline/issues/234
=> Allow premium user to access actionable variants and annotated variants

src/main/java/org/mskcc/cbio/oncokb/config/SecurityConfiguration.java
This is related to https://github.com/oncokb/oncokb/issues/3681
=> Expose drugs endpoint

src/main/java/org/mskcc/cbio/oncokb/service/UserService.java, src/main/java/org/mskcc/cbio/oncokb/service/impl/CompanyServiceImpl.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/CompanyResource.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/SlackController.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/UserResource.java, src/test/java/org/mskcc/cbio/oncokb/service/CompanyServiceIT.java, src/test/java/org/mskcc/cbio/oncokb/service/UserServiceIT.java
resolves https://github.com/oncokb/oncokb/issues/3685
=> Only renew tokens when activating user for PUT endpoint

src/main/webapp/app/oncokb-frontend-commons/src/components/RefComponent.tsx, src/main/webapp/app/oncokb-frontend-commons/src/lib/urls.ts
This fixes https://github.com/oncokb/oncokb/issues/3682
=> Fix NCT reference link

src/main/webapp/app/components/newAccountForm/NewAccountForm.tsx, src/main/webapp/app/config/constants.tsx, src/main/webapp/app/config/constants/terms.ts, src/main/webapp/app/pages/AccountPage.tsx
This fixes https://github.com/oncokb/oncokb/issues/3706
=> Add term related to AI model usage

src/main/webapp/app/pages/companyPage/CompanyPage.tsx
fixes oncokb/oncokb#3728
https://github.com/oncokb/oncokb-public/assets/24961694/54dd0268-d5ca-434e-8f7b-dca14c6a4b14
=> fixed create company users link style

src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java, src/main/webapp/app/components/newAccountForm/NewAccountForm.tsx, src/test/java/org/mskcc/cbio/oncokb/service/SlackServiceIT.java, src/test/java/org/mskcc/cbio/oncokb/web/rest/SlackControllerIT.java
fixes oncokb/oncokb-pipeline#327
=> Slack reports error and limits justification section

src/main/java/org/mskcc/cbio/oncokb/config/SecurityConfiguration.java
This fixes https://github.com/oncokb/oncokb-pipeline/issues/352
We released two new endpoints to premium user in this PR: https://github.com/oncokb/oncokb/pull/3714. We need to add them to Security Config
=> Add allVariantsOfUnknownSignificance endpoint to SecurityConfiguration

src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java, src/main/java/org/mskcc/cbio/oncokb/web/rest/slack/BlockId.java
This fixes https://github.com/oncokb/oncokb-pipeline/issues/350
=> Fix duplicate block id in slack payload

src/main/webapp/app/index.tsx
- Do not report API exception related to react mutation mapper
- Skip ResizeObserver loop completed error
This is related to https://github.com/oncokb/oncokb/issues/3736
=> Sentry updates

src/main/java/org/mskcc/cbio/oncokb/web/rest/ApiProxy.java
resolves https://github.com/oncokb/oncokb/issues/3711
=> Limit request methods on the proxy endpoint

src/main/java/org/mskcc/cbio/oncokb/web/rest/ApiProxy.java
part of oncokb/oncokb#3684 address json error formatting comments in the [core PR](https://github.com/oncokb/oncokb/pull/3771)
=> Proxy error response from core

src/main/webapp/app/components/newCompanyForm/NewCompanyForm.tsx, src/main/webapp/app/pages/companyPage/CompanyPage.tsx
resolves https://github.com/oncokb/oncokb/issues/3792
=> allow keypress events for textareas

src/main/webapp/app/pages/apiAccessGroup/APIAccessPage.tsx
Fixes https://github.com/oncokb/oncokb/issues/3793
=> Fix data download

src/main/webapp/app/pages/userManagement/UserDetailsPage.tsx, src/main/webapp/app/shared/modal/UserStatusModal.tsx, src/main/webapp/app/shared/table/UserTable.tsx
=> User is granted API access on approval

src/main/java/org/mskcc/cbio/oncokb/config/SecurityConfiguration.java
=> Fixed cancer type page link

src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/companionDiagnosticDevicesPage/companionDiagnosticDevicePage.tsx, src/main/webapp/app/shared/links/FdaSubmissionLink.tsx, src/main/webapp/content/files/companionDiagnosticDevices/companion_diagnostic_devices.json
This is related to https://github.com/oncokb/oncokb-pipeline/issues/586
=> Update CDx page with new data

src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx
This fixes https://github.com/oncokb/oncokb-pipeline/issues/587
=> Show alteration if it's a relevant alt of the original

src/main/webapp/app/oncokb-frontend-commons/src/components/SummaryWithRefs.tsx
Fixes https://github.com/oncokb/oncokb-pipeline/issues/628
This goes hand in hand with this PR from backend core https://github.com/oncokb/oncokb-public/pull/1195
=> Show newlines in descriptions

src/main/java/org/mskcc/cbio/oncokb/config/SecurityConfiguration.java
resolves https://github.com/oncokb/oncokb-pipeline/issues/197
=> update security config for sample api

src/main/webapp/app/pages/genePage/GeneAdditionalInfoTable.tsx
Resolves https://github.com/oncokb/oncokb/issues/3840
=> Fix refseq table style

src/main/webapp/app/pages/aboutGroup/AboutPageNavTab.tsx
related to https://github.com/oncokb/oncokb-pipeline/issues/677
I added a query parameter to hide the header and footer on the sop page.
=> Added contentOnly query Parameter to sop iframe

src/main/webapp/app/components/userMessager/UserMessage.tsx
Fixes https://github.com/oncokb/oncokb/issues/3890
=> Add banner for AACR 2025

src/main/webapp/app/components/userMessager/UserMessage.tsx
resolves https://github.com/oncokb/oncokb/issues/3909
=> add banner for asco 2025

src/main/webapp/app/routes/routes.tsx
Resolves https://github.com/oncokb/oncokb/issues/3957
Seems to be accidentally deleted in this [PR](https://github.com/oncokb/oncokb-public/pull/1190/files#diff-e2478ff01a71e5881b9f9a4fb4221dd14d742a27ced5dfa580cd2e1ed2d8dfa8:~:text=%2D-,%3CRecaptchaBoundaryRoute,/%3E,-393)
=> Add back password reset route

src/main/webapp/app/components/searchOption/SearchOption.tsx, src/main/webapp/app/components/tag/AlleleStateTag.tsx, src/main/webapp/app/components/tag/GeneticTypeTag.tsx, src/main/webapp/app/components/tag/tag.module.scss, src/main/webapp/app/config/constants.tsx, src/main/webapp/app/pages/annotationPage/SomaticGermlineCancerTypePage.tsx, src/main/webapp/app/pages/genePage/GenomicIndicatorTable.tsx, src/main/webapp/app/pages/genePage/SomaticGermlineGenePage.tsx, src/main/webapp/app/pages/somaticGermlineAlterationPage/SomaticGermlineAlterationPage.tsx, src/main/webapp/app/shared/header/GermlineSomaticHeader.tsx, src/main/webapp/app/shared/utils/Utils.tsx
resolves https://github.com/orgs/oncokb/projects/3/views/2?filterQuery=2024-week%3A%40current+bp&pane=issue&itemId=128355567&issue=oncokb%7Concokb-pipeline%7C885
=> remove allele state column and add tag in name column

src/main/webapp/app/components/searchOption/SearchOption.tsx, src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI-docs.json, src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI.ts
resolves https://github.com/oncokb/oncokb-pipeline/issues/856
=> add gene type badge to variants when searching
